<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Waters Navigated_watersNavigated</name>
   <tag></tag>
   <elementGuidId>991b9c1b-5801-44b5-9f94-4e791c467e56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#watersNavigated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='watersNavigated']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43caef18-1a70-489f-ac57-ab3dbb77cbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>watersNavigated</value>
      <webElementGuid>36ecb037-c237-43ed-bf7b-a810f4933089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d0f4c67-bfc5-49dc-99f7-6e9643e7e66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>b0cc2ff9-337d-469c-a109-5a2561d4471d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e74e485d-97eb-4593-8abe-0fa7d3f26b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39eb013b-e36f-43cc-8c47-14b17038f574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>watersNavigated_1440013438</value>
      <webElementGuid>c68ba38b-a646-40dc-b3ca-e60479144caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Lake Michigan</value>
      <webElementGuid>ade34f78-a9a5-403a-920b-b3ea4fdb1dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Lake Michigan</value>
      <webElementGuid>cb5ad1a9-9c75-47fe-a091-d7974198560b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;watersNavigated&quot;)</value>
      <webElementGuid>641eb953-5688-41f8-9ce6-eb9aeee00ca3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='watersNavigated']</value>
      <webElementGuid>bca35130-f1ec-4dcf-980d-19d219dc5649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[4]/div/div/div/div/div[2]/div/div[2]/div/div[3]/div[3]/div[2]/input</value>
      <webElementGuid>5b921129-6bc0-42e4-b67b-7976f3ea21f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/input</value>
      <webElementGuid>d0c78697-babf-47c1-ad09-2f1d7f3c2733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'watersNavigated' and @type = 'text' and @placeholder = 'Lake Michigan']</value>
      <webElementGuid>2ea442d8-a9ae-4b91-8e7c-17a598bc5122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
