<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UserName_UserName</name>
   <tag></tag>
   <elementGuidId>d1fa0537-864f-4eee-9dfb-822b4d4906a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4ce5353-638d-42b8-b50f-57df71f4ed59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>103669f0-ea68-449c-a40e-653ee5cc521d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>dcb49608-cd79-4e25-a361-b0f1f59a3be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>9285aeae-b588-49f2-8a8a-cec10efd090c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7bfe1ba-8a83-41fa-b010-90ba72f6bdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserName&quot;)</value>
      <webElementGuid>17f9857c-08ad-4c14-9473-d812eb2966ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserName']</value>
      <webElementGuid>5ac2b528-26a1-4bef-8d5c-755dc206bb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/div[2]/div/div[2]/div/input</value>
      <webElementGuid>a5199edd-afe0-4f0f-bae7-f8cf2d16f947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>282313db-927f-4c5b-a8b4-b5c2ae4b5e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserName' and @name = 'UserName' and @type = 'text']</value>
      <webElementGuid>511a72fb-9b8b-475a-ae44-c96091bf74d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
