<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Exposures_TextBox_RealEstate_Address</name>
   <tag></tag>
   <elementGuidId>591b1995-0d85-4f23-9daf-6e30b3778a85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressTypeAhead_address-7cvye50n0xx-googleAddressAPI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7843243-8ce5-474f-a3d6-b8ea178c1abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressTypeAhead_address-7cvye50n0xx-googleAddressAPI</value>
      <webElementGuid>7d9f67d4-3982-4309-8a9e-94b09d37c74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05d5d074-6419-40bb-86fc-1b3a8ef320cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>43d348ee-0a41-4938-93ca-fcdbf905341c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-address-7cvye50n0xx address-line1</value>
      <webElementGuid>d7ae1caf-3867-41ec-a25d-26013d413360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bdebf643-2459-4655-8be5-fd8093460b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>addressTypeAhead_address-7cvye50n0xx-googleAddressAPI_1440013438</value>
      <webElementGuid>aed45719-4f3d-4f73-9d9c-342dacc3ecdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>b7b79d2d-eb9c-4e66-8187-fec02a9420bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>19e3de9a-eb83-45ae-8575-69d56ba5b3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_address-7cvye50n0xx-googleAddressAPI&quot;)</value>
      <webElementGuid>7b3afd0d-a0f9-43c3-a2e7-96c36a7af0f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressTypeAhead_address-7cvye50n0xx-googleAddressAPI']</value>
      <webElementGuid>4f5c48d3-84e5-4caf-95b2-693ca07cbe5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>57830351-ba4a-47cd-b6c3-7a4bae62f7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>c08a7c1d-5074-45d9-a8a8-880ddd6d05da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressTypeAhead_address-7cvye50n0xx-googleAddressAPI' and @type = 'text' and @placeholder = 'Street address']</value>
      <webElementGuid>3f06bee4-e31c-4749-8800-a684fcc181ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
