<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_AccInfo_TextBox_Address</name>
   <tag></tag>
   <elementGuidId>c090c5ce-215b-4ecb-bc28-b5bec6fa8f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1507e9cc-740c-47cd-befd-ecf323742166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI</value>
      <webElementGuid>9eff2cec-c0d4-4d6e-b87d-9b80758a0241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62c49a0a-974e-4dd8-92b1-e5ce13754221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>86ea7fcc-5c89-490d-8b5e-fde29c3c7211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-contact-jp0dhqd1yn-address-7b9nflk4845 address-line1</value>
      <webElementGuid>0f5ab524-b103-46cd-89fe-68c69acfa763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0afa9c66-1130-474d-8e87-3cfd8fa3cab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI_1440013438</value>
      <webElementGuid>6d196ed6-b773-4fac-9143-a10333c6c568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>76e51822-eeb7-4f26-8991-7bc186f0231f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>26842f2a-e700-4c61-9eaa-9d0797a32c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI&quot;)</value>
      <webElementGuid>0fe17e1b-168d-4f43-9ade-265178acf737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI']</value>
      <webElementGuid>8a89a4cb-49fa-49a2-b8d6-5c050a82b39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>15c23790-1196-4320-827a-6eee7ccd50ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>ecd5132d-7539-4f10-833c-31466a05ada9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI' and @type = 'text' and @placeholder = 'Street address']</value>
      <webElementGuid>b0793c8c-c8db-40c6-8003-119f7ad96289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
