<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_AcctInfo_TypeList_1stAddress</name>
   <tag></tag>
   <elementGuidId>54a8dc2b-906c-4b36-9f90-20da51f3223d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI_typeaheadDropdownList']/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>88b8ba6a-2a84-48f1-ade4-69b3978aae97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f2059ea0-a367-4090-94fa-b39fc5ffc375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3fc06813-f8f4-4311-8b6d-d172de54fcce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR</value>
      <webElementGuid>56fed9d7-d5e3-49e1-88a4-a4fca1e61237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100 Main Street, Auburn, Indiana, USA</value>
      <webElementGuid>0687ac92-4dec-4ffa-a3a8-a7c25a28f39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI_typeaheadDropdownList&quot;)/li[@class=&quot;AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR&quot;]</value>
      <webElementGuid>2347f08d-2a1b-435a-a913-ef9f631eda52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI_typeaheadDropdownList']/li[2]</value>
      <webElementGuid>14d0a330-a7a1-4134-8bd7-3169e074121a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::li[2]</value>
      <webElementGuid>f2a16434-d56a-4511-9140-2ca9e89cac8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/following::li[2]</value>
      <webElementGuid>6e1f2ab6-b5d0-4721-b593-d6e89bca3ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 2'])[1]/preceding::li[4]</value>
      <webElementGuid>c455f936-c1ad-4505-ac6d-28de8f27d56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 3'])[1]/preceding::li[4]</value>
      <webElementGuid>879f78e9-b4b8-4990-a73f-11ec7926d237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100 Main Street, Auburn, Indiana, USA']/parent::*</value>
      <webElementGuid>3258deee-43c4-424e-bd53-669e814a4ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>8a83a48d-0211-470a-9957-09e45570a963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '100 Main Street, Auburn, Indiana, USA' or . = '100 Main Street, Auburn, Indiana, USA')]</value>
      <webElementGuid>4eae75ca-8008-4229-a5f5-ec4c9fae2689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
