<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_PrimaryPolicy_input_PropertyDamage</name>
   <tag></tag>
   <elementGuidId>01aece37-b911-460b-b53b-6fbf0f9147ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#propertyDamage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyDamage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b28c1ce-5a57-48d3-a161-66d494e68068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyDamage</value>
      <webElementGuid>15ae7e8b-afe5-4a5b-8f86-f3ded04b7d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fccfbfb5-fc39-4871-b3ea-12e05538b083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>0bcd68a3-6a75-410a-acf2-bbd60eb70e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>80b4c69f-0aa8-4fb0-8cbb-1d95de6ba2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e2346222-4ba8-48f0-9fd3-e47c78ef7baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>propertyDamage_1440013438</value>
      <webElementGuid>0018064e-f596-443c-901b-4b893312e29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>100,000</value>
      <webElementGuid>9f323bb4-076e-4fe8-a1e5-3e7a77ecffb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>100,000</value>
      <webElementGuid>88000d36-5c5d-45dc-ad3c-613ccb8b511b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>36e1b992-936e-4fa8-97e9-5e2c7043b6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyDamage&quot;)</value>
      <webElementGuid>1da33472-49f7-4552-b4e4-cec933fc904a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyDamage']</value>
      <webElementGuid>12c2f7b6-92c7-42a2-a5d8-c307cf29a208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[5]/div[2]/div/div/input</value>
      <webElementGuid>d6f67224-6582-4ad4-96df-992c4efabc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>79471bee-07ae-4cdd-a3c9-05987b923a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'propertyDamage' and @type = 'text' and @placeholder = '100,000']</value>
      <webElementGuid>136c9bc3-f54a-478f-a40c-d956b51182b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
