<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_DriverLastName</name>
   <tag></tag>
   <elementGuidId>2a0df305-6208-46da-be22-b7903ad853a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DriverLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DriverLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cff6ef6-17e6-4d38-8d36-ab64d7733c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DriverLastName</value>
      <webElementGuid>fdb92460-c2c1-40ee-99b3-bab8ec9dcb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e10f7317-4258-47ed-83fe-84e8b0aed18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>b5a02d5e-0062-4547-9d35-ffbf90c14e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2907d28e-4c66-4b01-81cb-86837f96e0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ba09f1c-bd9d-47c1-820e-8913f7caeb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>DriverLastName_1440013438</value>
      <webElementGuid>1adb241c-b2ce-4de0-b757-a97fcb1e7181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>d888f748-c8c0-4ba3-9549-0a3e80a8c15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>6e300615-8cfc-43a0-a06a-5e0c8d37a960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DriverLastName&quot;)</value>
      <webElementGuid>c2548eba-30b2-420a-8622-795b4784c9a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DriverLastName']</value>
      <webElementGuid>37ac0641-e8a0-4558-b0a1-cdffa5e68b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div/div/div[3]/div/div[2]/div/div/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>dd5c838f-9d70-4d6b-b5e8-fdfc1582d212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>27757709-2bb2-499e-9e79-9b3b8465ec04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DriverLastName' and @type = 'text' and @placeholder = 'Last Name']</value>
      <webElementGuid>c52862ff-5d06-4ab5-a509-9901a6a4dee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
