<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__openReserve</name>
   <tag></tag>
   <elementGuidId>788cf487-239d-4192-a951-c2c1b0233993</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#openReserve</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='openReserve']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4cd5f5d-64b7-4638-bbe0-ff622cbe6042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>openReserve</value>
      <webElementGuid>0adb4c15-ec1f-4bfd-8598-41cca25e146d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24207dab-91ee-41a6-b781-7a4e74d48fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__CurrencyField__currencyInput</value>
      <webElementGuid>9aeb8fce-24d8-45a8-8df1-c92eb1c16fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9210ff4b-0898-42a7-869f-e23ebca2ff4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>477f8582-9520-45e5-877d-1de1c3b1e748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>openReserve_1440013438</value>
      <webElementGuid>512fb6c6-0cb1-470e-b6c7-8de3fe79eb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>0,000</value>
      <webElementGuid>f777b395-c356-4696-9e9d-f15de2c29dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0,000</value>
      <webElementGuid>c23b2ab8-a318-4b4a-a697-54b3ceabb3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>0,000</value>
      <webElementGuid>42fcf866-4b2b-4215-9fad-93a595a7d3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;openReserve&quot;)</value>
      <webElementGuid>34d47f42-52b9-4460-8f17-fceaed4a4100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='openReserve']</value>
      <webElementGuid>f2c11d70-1a70-40fe-888e-64becb97c834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[7]/div/div/div/div/div[2]/div/div[2]/div/div[4]/div[2]/div/input</value>
      <webElementGuid>5e9e77fa-a54d-4599-bf57-afce2cd02b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>494f2726-d0e2-497e-8afa-aaf85b72a8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'openReserve' and @type = 'text' and @placeholder = '0,000']</value>
      <webElementGuid>b96ef40e-b96e-4cfb-8516-8bbdd270ca28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
