<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Loss_occurrenceDate</name>
   <tag></tag>
   <elementGuidId>9bed21da-6694-41f9-8f65-5bad12ed00d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#occurrenceDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='occurrenceDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0656124-4d55-4c7e-8d9b-9851a5c68cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b06af865-95d6-41fa-97f3-255e12c042d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>occurrenceDate</value>
      <webElementGuid>e642cc44-99df-4b2e-951c-463005429386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD/YYYY</value>
      <webElementGuid>bde4d303-6b5c-4767-b241-0f055646aafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>890fa0d0-a85e-4993-bc29-2a528527a41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicDatePickerField__datePicker jut__DatePickerField__datePicker react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>5fb0ec9f-63e2-4b20-8626-9a82f3154ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occurrenceDate&quot;)</value>
      <webElementGuid>fcfd253d-31ac-4546-b4fd-604c8056448b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='occurrenceDate']</value>
      <webElementGuid>2ac8c7ae-41e2-48bf-a9d6-1a2c63554724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[7]/div/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>419e3fb2-e3fd-4bc8-af7f-883c7cafb83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>d7361da3-e356-4305-9251-cd914625e9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'occurrenceDate' and @placeholder = 'MM/DD/YYYY']</value>
      <webElementGuid>da76c29b-2a03-4964-857d-2b400d854cf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
