<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__amountPaid</name>
   <tag></tag>
   <elementGuidId>dfceccb1-10e6-4cd6-823c-2dca4cdbb259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amountPaid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amountPaid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a95df9c-e17d-41b8-a86f-212a5afb397e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amountPaid</value>
      <webElementGuid>d655bdc8-116f-4688-8594-893be834d7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73a40b53-9c00-479d-9610-26224449f22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__CurrencyField__currencyInput</value>
      <webElementGuid>cbe87be9-439c-40c8-ae38-63b0e10b38b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>16439559-f5e6-4884-92e9-2629f0bd4683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>22d69cb2-6140-4ad1-b2ef-29bc66035799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>amountPaid_1440013438</value>
      <webElementGuid>659598c7-3889-4113-bc31-02d6a46fabff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>0,00</value>
      <webElementGuid>65842cf2-68e5-49ac-9d7c-3fc8eab67299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0,00</value>
      <webElementGuid>08fa6395-3e49-440b-a182-b5fdb0a067e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>0,00</value>
      <webElementGuid>9c12eafb-ca53-4612-abeb-816689c3f17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amountPaid&quot;)</value>
      <webElementGuid>4a0edd93-4743-48b6-a396-c775e58c4477</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amountPaid']</value>
      <webElementGuid>0ccc02f8-9a93-406d-aade-f9d95dcd250d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[7]/div/div/div/div/div[2]/div/div[2]/div/div[5]/div[2]/div/input</value>
      <webElementGuid>18894f0e-1439-486b-92d9-ef4da71d2563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>b48abab2-f69e-4ed0-8041-9b1aa99cd671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'amountPaid' and @type = 'text' and @placeholder = '0,00']</value>
      <webElementGuid>5ca703ac-98c8-46e1-9f7c-e8e8931553a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
