<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Portal_Regression_WC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fc8eb7ed-f3af-433e-b84a-50f3ab4b3c3d</testSuiteGuid>
   <testCaseLink>
      <guid>84e5ef68-abc8-4d16-becd-e8fa66e012df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80a67bab-e840-4fd3-830e-bb2eaeb0475e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e411ed6-edd9-41ef-9ead-e41b0bd3117c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb483c34-0f83-4b85-b576-638d5c693dc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2262e0f1-1dc8-4ad1-931d-1b9421ebc17e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>411072ae-a347-4fba-8141-fa1694caf441</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55119184-ac14-4c78-bf21-2e28952fca35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>618afd7c-8e71-4029-a6b4-c4dc485c7585</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa609d97-e685-4ae6-808e-ab63adcf623e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2d01f4e-004c-4e9b-ac69-3b9c01833ee9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f927c328-eabd-47d8-8f19-dc009dd7b813</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98206e40-4cb4-4ce5-b018-949984c8965a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20bd6d04-2678-4642-947a-b099afe0c3fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa78ad62-2bbd-4871-a949-680ddac61911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae639281-e567-4c26-8877-148e5979987b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d789e7f4-ef0b-41c9-9adc-4bc7f83ff886</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14da135f-d7f6-4781-b667-10f0f371be31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d86946e-211d-4fe0-848a-4471f514488d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ec336d3-6aa3-4c0b-bbbf-a82eb038b4b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2adfe3c-b573-44a2-969d-949304d05268</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a00dd96-389e-4907-80e3-8bd0575016ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a081bf1-183d-44dd-8fd7-1d9cb3b8d73d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b356b55-7c57-4d53-b1a1-7e4ceb6e800b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77932080-8b00-47a8-b8af-608482d727a6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
