<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Portal_Regression_WC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fc8eb7ed-f3af-433e-b84a-50f3ab4b3c3d</testSuiteGuid>
   <testCaseLink>
      <guid>84e5ef68-abc8-4d16-becd-e8fa66e012df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80a67bab-e840-4fd3-830e-bb2eaeb0475e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e411ed6-edd9-41ef-9ead-e41b0bd3117c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb483c34-0f83-4b85-b576-638d5c693dc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2262e0f1-1dc8-4ad1-931d-1b9421ebc17e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>411072ae-a347-4fba-8141-fa1694caf441</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55119184-ac14-4c78-bf21-2e28952fca35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>618afd7c-8e71-4029-a6b4-c4dc485c7585</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa609d97-e685-4ae6-808e-ab63adcf623e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2d01f4e-004c-4e9b-ac69-3b9c01833ee9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f927c328-eabd-47d8-8f19-dc009dd7b813</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98206e40-4cb4-4ce5-b018-949984c8965a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20bd6d04-2678-4642-947a-b099afe0c3fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa78ad62-2bbd-4871-a949-680ddac61911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae639281-e567-4c26-8877-148e5979987b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d789e7f4-ef0b-41c9-9adc-4bc7f83ff886</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14da135f-d7f6-4781-b667-10f0f371be31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d86946e-211d-4fe0-848a-4471f514488d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ec336d3-6aa3-4c0b-bbbf-a82eb038b4b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2adfe3c-b573-44a2-969d-949304d05268</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a00dd96-389e-4907-80e3-8bd0575016ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a081bf1-183d-44dd-8fd7-1d9cb3b8d73d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b356b55-7c57-4d53-b1a1-7e4ceb6e800b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77932080-8b00-47a8-b8af-608482d727a6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1ca50ed-8c29-403f-8106-85e043b6a48e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c3cf624-afa5-460a-a7eb-2abb4d95e554</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ea29158-375f-4974-8b19-4c85ff33abf6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1feeab6-7233-480c-98bf-4d0a3e189e1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1a88541-7552-433e-9e22-601ce03d4816</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d885073-8ecf-4198-ab4f-9261916ec840</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65d2924e-5112-4382-b411-3c8821c9093e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC006</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd8fcc1b-7d14-47fd-b630-946a8820ffce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdd2efda-8111-42bb-be5e-9b6df1e548e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9844737d-0cbc-47a4-8f12-c2ee800b4c3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f0d32b3-25fe-4231-a4b6-1245abfe6e32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>842b8a4c-6e5f-4b1d-9a94-27d45ed50dab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a875fd1-e6fd-4913-9e1e-5e79b1142051</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC007</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14ddb861-a56a-4c09-b5e4-4f9f3adb9508</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01d363d6-4b0e-4cd2-80ae-cacee108a45b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ae51e7-8e38-48e4-8f6c-e1fc37d4a8d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2d17ef8-ec13-4a9e-a7be-cb8014b7bee8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83cfbe50-451f-46a5-a93d-6fa5ce9d9fa0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>206028a8-df19-4564-bf98-d3da182e2be8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC024</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14ddb861-a56a-4c09-b5e4-4f9f3adb9508</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01d363d6-4b0e-4cd2-80ae-cacee108a45b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ae51e7-8e38-48e4-8f6c-e1fc37d4a8d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2d17ef8-ec13-4a9e-a7be-cb8014b7bee8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83cfbe50-451f-46a5-a93d-6fa5ce9d9fa0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d88499e-3b78-4fbb-9c3b-0faa002bdf1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC025</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14ddb861-a56a-4c09-b5e4-4f9f3adb9508</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01d363d6-4b0e-4cd2-80ae-cacee108a45b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ae51e7-8e38-48e4-8f6c-e1fc37d4a8d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2d17ef8-ec13-4a9e-a7be-cb8014b7bee8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83cfbe50-451f-46a5-a93d-6fa5ce9d9fa0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79fcf27f-9f97-4980-8a9a-9b8af3fe0dc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_E2E_Regression/HMIC-WC-PORTALS-E2E-TC027</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14ddb861-a56a-4c09-b5e4-4f9f3adb9508</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01d363d6-4b0e-4cd2-80ae-cacee108a45b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ae51e7-8e38-48e4-8f6c-e1fc37d4a8d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2d17ef8-ec13-4a9e-a7be-cb8014b7bee8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83cfbe50-451f-46a5-a93d-6fa5ce9d9fa0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
