<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0068-DeLordy 020590068DerickLordy</name>
   <tag></tag>
   <elementGuidId>b4373bb7-5d90-4845-9253-43170adf7a39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-8-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-8-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61c8047f-3d31-4f87-967e-5dc9cc7f2cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicGenericSelectControl__option jut__GenericSelectControl__option jut__GenericSelectControl__optionFocused css-1n7v3ny-option</value>
      <webElementGuid>6bad58e2-d111-4cba-ad6a-6baa7434ddb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-8-option-0</value>
      <webElementGuid>8c5c16b8-4a88-4ac5-8a19-d8a9af2e7d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>eea0e950-0dff-49a6-a8f7-f5ac1a40c7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0068-DeLordy 020590068DerickLordy</value>
      <webElementGuid>fec65b09-06cf-4361-b2e1-4b4738994bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-8-option-0&quot;)</value>
      <webElementGuid>cf80e585-612d-4039-8140-c19328e8c7d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-8-option-0']</value>
      <webElementGuid>1a23c982-bd33-4a2f-ac52-3b1140d48b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'react-select-8-option-0', '&quot;', ')')])[1]/following::div[4]</value>
      <webElementGuid>7a42d7db-347e-4e0f-a640-6f02ac506784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[5]</value>
      <webElementGuid>33522193-4e7e-475b-bb1e-e85a87d76b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0068-DeLordy 020590068DerickLordy']/parent::*</value>
      <webElementGuid>48974a22-883d-42a3-a264-3c424a6854b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div</value>
      <webElementGuid>d2b5cd61-c630-40a1-b891-f117bb2935bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-8-option-0' and (text() = '0068-DeLordy 020590068DerickLordy' or . = '0068-DeLordy 020590068DerickLordy')]</value>
      <webElementGuid>fcdaefd9-aae9-4532-a261-9532b9063c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
