<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_addressTypeAhead_contact-awbk_934847</name>
   <tag></tag>
   <elementGuidId>52b46658-d9cd-4c7a-ad7b-71523156ab0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressTypeAhead_contact-awbktxmdbhl-address-2u07t0dtc8k-googleAddressAPI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressTypeAhead_contact-awbktxmdbhl-address-2u07t0dtc8k-googleAddressAPI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a3c195b-8f72-4ee8-a4f0-47f49e025152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-awbktxmdbhl-address-2u07t0dtc8k-googleAddressAPI</value>
      <webElementGuid>f4b572ca-5cde-4e28-93a0-2f383e3807dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>363677bb-9f49-4cd2-bc21-e6e984bd8ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>f6eeff90-7e60-47bc-b9d2-cb6fb777b893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-contact-awbktxmdbhl-address-2u07t0dtc8k address-line1</value>
      <webElementGuid>957b303e-86e4-4faa-b5a6-40891bd357a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06cf3725-be55-4126-aa71-8194fad1e866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-awbktxmdbhl-address-2u07t0dtc8k-googleAddressAPI_1440013438</value>
      <webElementGuid>1865dc65-c7b6-4a20-ad6f-7c35f1ea5bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>dab05a9d-621a-4c0b-8d84-d6ccc35a859e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>549a6daf-ae91-4cc3-a7db-3ccb0c955bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_contact-awbktxmdbhl-address-2u07t0dtc8k-googleAddressAPI&quot;)</value>
      <webElementGuid>ecedca04-a0fa-44fc-bfb7-0e9f04878736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressTypeAhead_contact-awbktxmdbhl-address-2u07t0dtc8k-googleAddressAPI']</value>
      <webElementGuid>91cfe526-0ee1-4d80-b71a-e7a1726e9402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>d0eeb61b-e03d-4ed4-9339-1ea7e698f8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>560a616a-a430-4148-9b8e-146b9e52c0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressTypeAhead_contact-awbktxmdbhl-address-2u07t0dtc8k-googleAddressAPI' and @type = 'text' and @placeholder = 'Street address']</value>
      <webElementGuid>f052aa00-3c3b-4288-b983-af94712ae360</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
