<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0011 - Farm  Market Or Truck</name>
   <tag></tag>
   <elementGuidId>f8325c57-5de7-419e-9a00-cf31723290bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-15-option-4 > div.jut__LookupField__item > div.jut__LookupField__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-15-option-4']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f45b81b3-6c99-4238-a953-fa6e32729c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__LookupField__title</value>
      <webElementGuid>596bfb02-8c7a-4354-b82a-e73efd3c0d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0011 - Farm:  Market Or Truck</value>
      <webElementGuid>098753cb-ba3b-4bf1-b58e-510cea616b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-15-option-4&quot;)/div[@class=&quot;jut__LookupField__item&quot;]/div[@class=&quot;jut__LookupField__title&quot;]</value>
      <webElementGuid>e33d98c8-76e4-4a1e-bfc6-aa0686757ef5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-15-option-4']/div/div</value>
      <webElementGuid>5c735143-5966-4aad-a77a-da78e3f09828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[4]/following::div[3]</value>
      <webElementGuid>56ed46bc-c6a2-4249-b6c9-35959df68ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[3]/following::div[7]</value>
      <webElementGuid>ea1c1761-77a9-425c-aa87-445fd0901ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[5]/preceding::div[1]</value>
      <webElementGuid>f6e27a33-6379-4daa-aa15-e16ce5e50b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[6]/preceding::div[3]</value>
      <webElementGuid>f7c8a456-a1a7-4856-9546-3a10eec21586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[5]/div/div</value>
      <webElementGuid>98fe713d-4f6c-4b1d-9492-08320cd4d629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0011 - Farm:  Market Or Truck' or . = '0011 - Farm:  Market Or Truck')]</value>
      <webElementGuid>57792db0-6b3d-4baa-90b2-999645f091e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
