<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__totalPayroll</name>
   <tag></tag>
   <elementGuidId>718a7498-a2f9-4299-8772-c72dec829501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#totalPayroll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='totalPayroll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0b423c0-0029-494b-b066-bc55a1e6ec48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalPayroll</value>
      <webElementGuid>611b5a49-0477-4311-a1f0-d9e2a36affb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5935ae6a-12cf-45fd-b4fa-db668c416621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>b5ad4df3-0ea8-4bcb-b7a2-8e5e49c6e3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>7f7ee4b3-ef38-4e07-a005-36430698b6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e80f6ee5-b2b2-4356-8f29-2238e0fdb302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>totalPayroll_1440013438</value>
      <webElementGuid>e0edc08c-726f-4cd2-b8ee-7f0a33043680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>$1,000</value>
      <webElementGuid>c563b9cc-9fa6-4909-a3ae-0461dfbabd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>$1,000</value>
      <webElementGuid>83367637-405b-4abc-9db0-62cde932bea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>6a961446-2280-491d-8915-45d9bb4a82fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalPayroll&quot;)</value>
      <webElementGuid>f1e41c18-c01b-4616-a2e0-6779361c8b1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='totalPayroll']</value>
      <webElementGuid>81ff0d81-c30f-4791-8330-ab0ad727059b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/div/div/div/div[3]/div[4]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>103875a9-32b6-4727-bc4c-5ac0640e57f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>8f0ae027-144b-4875-a7fc-f84854b9222d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'totalPayroll' and @type = 'text' and @placeholder = '$1,000']</value>
      <webElementGuid>24787675-30a2-410d-baca-8aa3bbf6a0d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
