<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__numFullTimeEmployees</name>
   <tag></tag>
   <elementGuidId>3f2862cc-38a6-4a43-8ad2-f7fe35ed1237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numFullTimeEmployees</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numFullTimeEmployees']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3ade5e0-a04a-4497-b6c5-022f77f3e699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numFullTimeEmployees</value>
      <webElementGuid>dab042f4-7dca-48df-9654-722222ae3679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>461d8344-f52b-4bba-a897-fea7570f7628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>d375226f-6097-42d4-9fad-078f6d60562b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>04138f9e-5a6b-416b-8d8f-0632dfa86c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8a3f0975-c392-4759-ae8e-8ab56c453182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>numFullTimeEmployees_1440013438</value>
      <webElementGuid>a3b4f361-b23a-42d8-81d8-a0d4de605d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>19018f20-219b-4e17-8b3e-674997355edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8805e76f-6c38-43e3-b383-014c48a929b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>c13aa36f-412f-43f5-901e-d37c9e67cca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numFullTimeEmployees&quot;)</value>
      <webElementGuid>637c4eff-9879-4348-a535-7a414935d3b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numFullTimeEmployees']</value>
      <webElementGuid>7c3e0ae2-862f-4bed-9d3b-aae3c66e7fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/div/div/div/div[3]/div[4]/div/div/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>61e78157-3ee3-429f-afb6-9d34c7b9fcab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/input</value>
      <webElementGuid>e69aaaee-67b6-484b-a6bf-b97a07dd8254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'numFullTimeEmployees' and @type = 'text' and @placeholder = '5']</value>
      <webElementGuid>5350878b-7323-468e-8d43-dbff896e981e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
