<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>renewal button</name>
   <tag></tag>
   <elementGuidId>29f61bf7-fccf-49a8-8c6d-1d80a21ac1f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='renewChangePaymentPlanCard']/div/div/div/div/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mir.mi-check.jut__CheckboxField__checkboxIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>924197c5-fd1e-46d8-8e85-601b1365de26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mir mi-check jut__CheckboxField__checkboxIcon</value>
      <webElementGuid>688b58db-a363-4cdd-820d-e922b6e5f572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e868c05-ee03-4dc5-be59-756bad5796b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renewChangePaymentPlanCard&quot;)/div[1]/div[@class=&quot;jut__FieldComponent__fieldComponent smallOverline&quot;]/div[@class=&quot;jut__FieldComponent__contentContainer jut__FieldComponent__controls&quot;]/div[@class=&quot;jut__CheckboxField__checkbox&quot;]/span[@class=&quot;jut__CheckboxField__checkboxElement&quot;]/i[@class=&quot;mir mi-check jut__CheckboxField__checkboxIcon&quot;]</value>
      <webElementGuid>a2c32a37-963b-445b-89ac-92d6d9a34b72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renewChangePaymentPlanCard']/div/div/div/div/span/i</value>
      <webElementGuid>faf2b022-1c1a-4390-b4a0-dd4dda488bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/i</value>
      <webElementGuid>30ae4d6e-a3dc-485d-a8f3-bec741e51fc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
