<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Occupancy  Interest_occupancyAndInterest</name>
   <tag></tag>
   <elementGuidId>2c926179-fd2b-46ed-8883-7132fe668952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#occupancyAndInterest</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='occupancyAndInterest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>642c0dbb-7c09-4e57-887e-59445cd29d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>occupancyAndInterest</value>
      <webElementGuid>963df508-122d-4c10-8014-fe55a436b73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d930448-63d0-4f01-bc6e-34b1ad90f92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>5d8a75ce-bf86-49d5-a0e9-15d7f12c31dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a09fe0bb-8645-40d7-95a1-f2d71d53647e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8167fe30-2b2b-4e1f-a467-dae745190b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>occupancyAndInterest_1440013438</value>
      <webElementGuid>06cf113a-9cf9-475f-9db2-dce8e621cf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Owner, lessee, etc..</value>
      <webElementGuid>438ad401-07e8-49b2-a127-0c50ea39d0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Owner, lessee, etc..</value>
      <webElementGuid>929ba293-f76a-4fb6-84e0-87fa31e521fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occupancyAndInterest&quot;)</value>
      <webElementGuid>7ec1ee38-e877-4893-a65d-4f3c2e90fea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='occupancyAndInterest']</value>
      <webElementGuid>135fa658-c041-479e-af50-4e7a58bd8265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>da9a5751-2ccd-4dd5-a797-269f18072cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>be348a95-419b-47d9-9895-37c1cbc826ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'occupancyAndInterest' and @type = 'text' and @placeholder = 'Owner, lessee, etc..']</value>
      <webElementGuid>127099ac-8394-4e92-bda3-384c01b9817c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
