<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_address-x584jj71l7j-city</name>
   <tag></tag>
   <elementGuidId>9d9911ac-e041-41c8-87ba-45abc127d63a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-x584jj71l7j-city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-x584jj71l7j-city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f6883ec-cb7c-473e-80d0-c281411511f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-x584jj71l7j-city</value>
      <webElementGuid>07197941-9c72-4d9a-bb2c-fe21fa99169d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c271b532-6e6a-4e11-8845-6ee961dc2509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>6158bbaf-0a6f-4145-8a30-09db437aece9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-address-x584jj71l7j disabled-address-level2</value>
      <webElementGuid>bd030628-892f-439f-baa7-43114d2bc22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29bcd6e0-176a-4ba2-8c4b-271321e77b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>address-x584jj71l7j-city_1440013438</value>
      <webElementGuid>54ecf93b-bbe3-417a-b2ba-a7007c0c2176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>3910abcd-a50b-43d1-b71b-2a4de504c63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>e38d0899-0cfc-4f7a-b8d8-0eee68444fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-x584jj71l7j-city&quot;)</value>
      <webElementGuid>55e7f758-1ac3-4865-92f2-1122e1063ed7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-x584jj71l7j-city']</value>
      <webElementGuid>21245e78-9dcf-4bb4-8a68-33a481082815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>dc0bb4d1-33b7-42b8-95d2-f62b9a85308c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>d8beea5d-48da-463e-a7be-63d6f22634b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address-x584jj71l7j-city' and @type = 'text' and @placeholder = 'City']</value>
      <webElementGuid>b715b24b-1161-4c62-99b2-126a35c6d059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
