<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>agency</name>
   <tag></tag>
   <elementGuidId>d7af88cf-1562-43ab-90ac-93ba78f4c2ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selectedRenewBillingMethod-wrapper']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.jut__GenericSelectControl__control.jut__GenericSelectControl__controlFocused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e5a0058-0066-42df-81b7-221a5e29b159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__GenericSelectControl__control jut__GenericSelectControl__controlFocused</value>
      <webElementGuid>24374d42-54dd-4fd4-b6eb-47b518822977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agency</value>
      <webElementGuid>09ca6199-58e0-45e1-91b7-6214555544bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedRenewBillingMethod-wrapper&quot;)/div[@class=&quot;jut__GenericSelectControl__control jut__GenericSelectControl__controlFocused&quot;]</value>
      <webElementGuid>c9abef7c-ccf5-4f7b-8988-74c5d43e5fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectedRenewBillingMethod-wrapper']/div</value>
      <webElementGuid>c50a4b36-6658-4f31-80e8-fa0589888955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing method'])[2]/following::div[4]</value>
      <webElementGuid>7394fd86-bd41-45f5-9bfc-2b035e4f0af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change payment plan at renewal?'])[1]/following::div[8]</value>
      <webElementGuid>5dacbc03-c2ae-44ae-9ebe-769c9ea7d4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment plan'])[1]/preceding::div[5]</value>
      <webElementGuid>1d9deee3-333d-497f-a7c6-06338e2985a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>238feb68-098f-4220-bc2c-e1958d269cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Agency' or . = 'Agency')]</value>
      <webElementGuid>23274f04-a48d-4c3c-83b1-d2d8c8bc319b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
