<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Limit Per Person_perPerson</name>
   <tag></tag>
   <elementGuidId>828e43bd-fd00-4655-82ec-a7a51caa4e0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#perPerson</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='perPerson']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48499ea6-a56d-47f1-aea6-34fde854a1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>perPerson</value>
      <webElementGuid>fe820521-6995-4c58-9b5c-6b00e3875fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6ac0e05-ff5e-4499-86e6-2df888e5623b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>192c4955-3193-405d-a0d0-adb83582a012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>510dfa98-311f-4252-9345-37ac559bb308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>447f0580-ed30-4f11-96c4-049897c0cf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>perPerson_1440013438</value>
      <webElementGuid>e8a7de60-ab00-420c-97bb-5c8ba4ad9d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>500,000</value>
      <webElementGuid>69c5c883-b134-4dc5-96b2-c160bc629fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>500,000</value>
      <webElementGuid>4e5ef809-05eb-4b20-8e6c-32719fc43cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;perPerson&quot;)</value>
      <webElementGuid>b699fe33-1124-443f-b92a-0d5db03ceb90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='perPerson']</value>
      <webElementGuid>3e271b6e-8bbf-4db9-b1e2-27e57a9c2b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>403a64b8-cdcd-4e1f-a6a9-2ebcd919a3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>59f5ecd2-bc69-4fb5-b1fa-721ec6079562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'perPerson' and @type = 'text' and @placeholder = '500,000']</value>
      <webElementGuid>f83a44f9-6ba8-49a2-ac02-bac20fe262b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
