<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Damage_propertyDamage</name>
   <tag></tag>
   <elementGuidId>68fd993f-e818-46b9-80ad-9c9f4151a87a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#propertyDamage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyDamage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ce6b3bb-cb1a-4a92-ae4a-31c368018420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyDamage</value>
      <webElementGuid>9e837815-67e5-4c0f-a4f3-79003d76e749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38748340-6ed4-4749-9b9c-2b99dd0de873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>feecb5a4-5b32-4052-97e0-4debf2309c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>bc042cec-bda2-40c0-8589-42a7f9ad22b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b35b7d4-0564-483e-b6d9-ea7e52eba968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>propertyDamage_1440013438</value>
      <webElementGuid>dd79cae9-404e-49d2-aca6-685671ea74c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>100,000</value>
      <webElementGuid>2d2cc876-dcc7-4cb1-9453-843bec4d0243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>100,000</value>
      <webElementGuid>e0fc2356-43ec-47b4-ba15-04309ccb0bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyDamage&quot;)</value>
      <webElementGuid>75a0ecf7-d0aa-4a30-b68d-3d565c854b42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyDamage']</value>
      <webElementGuid>284b4976-18b9-4bb0-aa04-080a8320d32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[4]/div[2]/div/div/input</value>
      <webElementGuid>535f281c-07b9-402b-8cd2-2b81e95d76ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>2e4bac84-3ba7-4f28-b1ac-0bd37f28ff8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'propertyDamage' and @type = 'text' and @placeholder = '100,000']</value>
      <webElementGuid>0c9dd114-2be7-4ace-ada8-4086b1f32974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
