<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Accept</name>
   <tag></tag>
   <elementGuidId>0dcfbfe4-c9a1-4ede-b829-74984fa4f22e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='includeUmUim']/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.jut__RadioButton__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fe7279c0-861a-45c9-b6b6-66672bd429ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>includeUmUim_Accept</value>
      <webElementGuid>fc9cb2c3-a42a-42c0-8e90-eecd6e442517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4451aad7-fe2b-463f-a2c9-b491152c4c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__RadioButton__label</value>
      <webElementGuid>4065ea94-9ae5-47db-89cf-a599818e8d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>e5459c26-f24d-416f-a356-3154d62bd264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;includeUmUim&quot;)/div[@class=&quot;dynamicRadioButton__radioButton jut__RadioButton__radioButton&quot;]/label[@class=&quot;jut__RadioButton__label&quot;]</value>
      <webElementGuid>14388285-951b-4943-835e-ec43b8c57559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='includeUmUim']/div/label</value>
      <webElementGuid>2d82ffe0-344a-4862-9bad-551b9f2de61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include UM / UIM Coverage?'])[1]/following::label[1]</value>
      <webElementGuid>464f6852-1952-459e-8be3-d043efce897c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autos'])[1]/following::label[2]</value>
      <webElementGuid>8a0f09f1-cffb-41c0-9b75-615a57f0d2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/preceding::label[1]</value>
      <webElementGuid>0738b26a-aa03-460f-9178-ebdb58986961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label</value>
      <webElementGuid>2b755360-aeed-4ea3-8ab2-9b9d43e9b642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>fc80ec12-cf7e-46df-bbb5-2545009ce52f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
