<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_addressTypeAhead_address-4ai0_de3c63</name>
   <tag></tag>
   <elementGuidId>75bb5d3c-4eac-4ca3-864e-dd03ea533ea2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressTypeAhead_address-4ai0500xorf-googleAddressAPI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressTypeAhead_address-4ai0500xorf-googleAddressAPI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52af441d-01c8-49bb-ac1b-d6294ce8d9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressTypeAhead_address-4ai0500xorf-googleAddressAPI</value>
      <webElementGuid>1df1ce9e-ac84-44a7-93ed-f6e739931e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20474c9d-814e-4b8d-ac58-d759c5b46f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>e1663864-0075-4829-8f82-561657d4ea83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-address-4ai0500xorf address-line1</value>
      <webElementGuid>bbf9e460-0c03-48f9-b818-d67b1aa32b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2576b97d-cfda-4977-a718-a1793ec0b856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>addressTypeAhead_address-4ai0500xorf-googleAddressAPI_1440013438</value>
      <webElementGuid>2a0a393f-fde8-4532-bca7-3e085a3b35ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>edf87cb1-66a2-4252-b480-570250a53949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>60ba87f2-0b35-47f9-b7c3-77ff03d9a67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_address-4ai0500xorf-googleAddressAPI&quot;)</value>
      <webElementGuid>4a1fef7f-f172-470f-966e-51ddc6ae7751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressTypeAhead_address-4ai0500xorf-googleAddressAPI']</value>
      <webElementGuid>099bc757-baea-45b6-82b5-57d7cebfab04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>cff707fa-ac93-473e-855d-ccf4efb9f05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>c60ebcb9-eb4e-4bbe-b69b-d9bf0c2fa459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressTypeAhead_address-4ai0500xorf-googleAddressAPI' and @type = 'text' and @placeholder = 'Street address']</value>
      <webElementGuid>5ac4dffc-d85c-4e6d-a256-473b3edbce47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
