<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_address-4g3mytlyz8-city</name>
   <tag></tag>
   <elementGuidId>908248af-7574-417e-af9b-3b988d12d88e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-4g3mytlyz8-city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-4g3mytlyz8-city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54510c33-fcac-4a6f-90df-d5994514ead7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-4g3mytlyz8-city</value>
      <webElementGuid>6bc6eeaf-cf9c-4f85-82e4-ecae2a4e84e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2163f424-000a-470f-925c-98a60e1f656b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>27bc2b7c-ae04-44c9-9bc1-3a71a6923463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-address-4g3mytlyz8 disabled-address-level2</value>
      <webElementGuid>a41e816e-e2b8-4ab1-8849-35aec6aa6db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61040389-bc10-4cd3-8a55-6cf3f2aef57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>address-4g3mytlyz8-city_1440013438</value>
      <webElementGuid>0fbc7f74-b7fb-483a-a037-dddf8a6d86f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>4f36b196-4a5c-433c-9e67-e9aacd32d730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>66cbe5a3-f3d9-4ce7-813c-f3ffb537d1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-4g3mytlyz8-city&quot;)</value>
      <webElementGuid>62056752-bc1f-4cb0-b552-02fea6c49763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-4g3mytlyz8-city']</value>
      <webElementGuid>fa33c5cb-be62-460e-b629-7afe22462844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>22ed5be9-39a3-4b51-94a1-d6ce7baea633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>fefd65f5-c2be-45b4-ab3e-0c0f77d02f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address-4g3mytlyz8-city' and @type = 'text' and @placeholder = 'City']</value>
      <webElementGuid>7293b846-0054-41fb-8e12-d62229b6adca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
