<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_addressTypeAhead_address-4g3m_58918c</name>
   <tag></tag>
   <elementGuidId>88284d9a-3f9b-461a-b831-fe14618a6417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressTypeAhead_address-4g3mytlyz8-googleAddressAPI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressTypeAhead_address-4g3mytlyz8-googleAddressAPI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bf5250b-2d82-4149-878f-592645e98838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressTypeAhead_address-4g3mytlyz8-googleAddressAPI</value>
      <webElementGuid>a0f1d49a-93bd-49ba-a340-0457e0e4ebfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>236f3594-9fc0-4c5b-9c8a-db4bae473dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>6d642a59-2f8d-43af-9849-f02226f96a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-address-4g3mytlyz8 address-line1</value>
      <webElementGuid>5ca1cbfa-aef8-42b9-a2c6-8f492b8f6957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>99b47933-2b91-4fe4-a125-2b15a684c45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>addressTypeAhead_address-4g3mytlyz8-googleAddressAPI_1440013438</value>
      <webElementGuid>b889e4d5-bc4a-4c1b-b57a-d219cbbee7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>4e0791e5-f1a0-439b-8bfb-4e405972da27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>d0068ee7-864f-45a3-979e-ed53358e9aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_address-4g3mytlyz8-googleAddressAPI&quot;)</value>
      <webElementGuid>ba0d8cab-9bdf-4c88-84ec-1b570138b0e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressTypeAhead_address-4g3mytlyz8-googleAddressAPI']</value>
      <webElementGuid>831ba668-3b01-4252-b117-346ac55bfaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>4cdda645-f543-4169-8fbb-cbdbc1a1e9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>cc95d738-55b8-45a6-8733-9de3ba7ed346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressTypeAhead_address-4g3mytlyz8-googleAddressAPI' and @type = 'text' and @placeholder = 'Street address']</value>
      <webElementGuid>f6fcf128-a6fc-4f91-a0a8-8bc9b7339b6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
