<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_address-4ai0500xorf-city</name>
   <tag></tag>
   <elementGuidId>673a6ce0-1867-48e2-a3b2-0cb222c68cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-4ai0500xorf-city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-4ai0500xorf-city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b81a29b8-2324-43a8-9b8f-1f8b86404d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-4ai0500xorf-city</value>
      <webElementGuid>6fe48d08-ac38-4fa4-967c-f801b311247f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93232ad4-b482-418f-8f46-841d7ac2f471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>8c8237f9-d4be-4fe0-9115-6f7ce79129a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-address-4ai0500xorf disabled-address-level2</value>
      <webElementGuid>1261ce4d-20fc-4581-bb65-c0b758860ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>599f5d75-dc7c-45c4-8ca3-034b84a63f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>address-4ai0500xorf-city_1440013438</value>
      <webElementGuid>ec731e85-15cc-4959-a1d6-238ff708f2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>c7204992-0a7b-49c9-b127-36926c9a1b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>6d33ffdb-9af7-4e3a-b1d2-5e91a1941480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-4ai0500xorf-city&quot;)</value>
      <webElementGuid>f115fecf-bf15-4c9a-89db-0915b6192cfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-4ai0500xorf-city']</value>
      <webElementGuid>13164fdb-22b8-4ee7-b563-54c62c5dc3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>c328e35a-f011-4da2-b74f-84d2360bc90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>093e8359-4997-49bf-889b-330f0956b4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address-4ai0500xorf-city' and @type = 'text' and @placeholder = 'City']</value>
      <webElementGuid>79c11c20-84de-4c7c-9078-2308a044657a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
