<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Waters Navigated_watersNavigated</name>
   <tag></tag>
   <elementGuidId>a4dd9639-f367-434f-a6d0-9e4834881950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#watersNavigated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='watersNavigated']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bec76220-67a5-4081-bce4-8f975f8b20ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>watersNavigated</value>
      <webElementGuid>da22f34b-13b4-466a-9821-ac042b55547b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>885565e6-d404-4498-912c-04ef41c08931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>1af2ae17-70de-4fad-9011-4dff6802c0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e9966dec-1a4a-440d-b125-f0712b2697aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dcc9d287-00a9-414a-ae7b-c57fcfc3d7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>watersNavigated_1440013438</value>
      <webElementGuid>21cb389c-e6cd-4860-b48c-9cca413ab08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Lake Michigan</value>
      <webElementGuid>7ad2ef27-93d8-4a03-8282-dad2f9038f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Lake Michigan</value>
      <webElementGuid>372c736f-9d17-4030-a4c9-7b40578975f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;watersNavigated&quot;)</value>
      <webElementGuid>c1997395-7350-44cf-b239-91f5d571853a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='watersNavigated']</value>
      <webElementGuid>40c3cdad-d242-42a5-9fbb-5c96b13a5dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[4]/div/div/div/div/div[2]/div/div[2]/div/div[3]/div[3]/div[2]/input</value>
      <webElementGuid>83a2e407-2a3e-4e7b-ba3a-6c83925b96e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/input</value>
      <webElementGuid>fdc19a4f-f89a-4e96-9db7-32c80b0ad9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'watersNavigated' and @type = 'text' and @placeholder = 'Lake Michigan']</value>
      <webElementGuid>a33c9261-25d0-4c36-a404-882301ecdbc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
