<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_address-5izhviukmor-city</name>
   <tag></tag>
   <elementGuidId>3c7274c7-80a3-416b-a5bd-f90692ac4a59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-5izhviukmor-city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-5izhviukmor-city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fb539eb-4349-438d-8cb3-e46741c9955d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-5izhviukmor-city</value>
      <webElementGuid>4ac6afb0-1129-4398-8647-4d1b6be1db5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc6931f3-0edd-45da-8626-1f849eda97d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>fff47016-7d7a-45c3-97f3-060e22af6639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-address-5izhviukmor disabled-address-level2</value>
      <webElementGuid>419cbbca-8aac-466d-9f38-b794c7b1f590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>05d25eb3-bcff-471a-9c05-b31cff7741b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>address-5izhviukmor-city_1440013438</value>
      <webElementGuid>62179c9d-b067-4ab0-8308-be9818cdc55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>47854991-0fac-44f7-90f4-5885b22caaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>d1e8e902-f1bf-4186-bff9-625ecb0b3415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-5izhviukmor-city&quot;)</value>
      <webElementGuid>7376a6ca-33a5-4564-82dc-013a9c3c5d89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-5izhviukmor-city']</value>
      <webElementGuid>45f1c70f-9099-4472-8dda-f6ddc86cd4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>bee083bf-e27e-440b-9a0c-32aa89ee5563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>e2b608e6-d731-47ab-a3e2-6de98d00c7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address-5izhviukmor-city' and @type = 'text' and @placeholder = 'City']</value>
      <webElementGuid>5fb2c9d8-5db8-4838-9b0a-654e7eb4cdc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
