<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Horsepower_horsepower</name>
   <tag></tag>
   <elementGuidId>bf647398-a378-41b2-b10c-d4d0927712b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#horsepower</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='horsepower']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9704903-6657-4e59-bcfe-7e5f94392a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>horsepower</value>
      <webElementGuid>ae23313b-1a0c-4149-a7eb-c922a3fc7824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3473b16-0edf-460a-998b-9a5ab1b3f009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>1fbdbc82-21e6-4c3e-adef-f780ce053d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1939370a-b145-4a9f-882b-519e1ab65d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b9f801d9-45cd-4eba-b553-2a4874c45428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>horsepower_1440013438</value>
      <webElementGuid>9dabbb7b-8ceb-4afc-b423-c05fe43754d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>011c2ab2-b4a4-4a4c-809a-58e1b6545f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>92307003-c431-4e0b-a749-8f8c57b33e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horsepower&quot;)</value>
      <webElementGuid>4ce8105f-cf79-4e7b-9db1-51b416ca94c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='horsepower']</value>
      <webElementGuid>a8945d21-b96f-4f44-b333-e0414bbe22ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[4]/div/div/div/div/div[2]/div/div[2]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>f2866c4e-c610-487f-b1d8-d7c860512038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>ecb11444-fd61-4693-a2c0-f8bf340a9ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'horsepower' and @type = 'text' and @placeholder = '400']</value>
      <webElementGuid>a2828e55-bb74-4359-9345-28f4f6c23eed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
