<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZIP Code_address-4g3mytlyz8-zip</name>
   <tag></tag>
   <elementGuidId>72757e00-16ed-4014-8cc0-cb6e7105a92d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-4g3mytlyz8-zip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-4g3mytlyz8-zip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2e966ad-7f08-4154-901e-6232ac8f05b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-4g3mytlyz8-zip</value>
      <webElementGuid>27757b53-48a1-4a75-b069-3a7ce3abfcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b34b5884-34e4-4c62-b223-e5fd0e264e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>8b7955fc-2bd3-4c8d-9be6-fdc4e5583a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-address-4g3mytlyz8 disabled-postal-code</value>
      <webElementGuid>165b7cb8-d5e9-45e7-89ff-a9d633f66959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0e4485e8-4e27-4637-a0a5-2483892529da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>address-4g3mytlyz8-zip_1440013438</value>
      <webElementGuid>702cea46-a5f1-4fca-b584-f94b6fdbd445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>d994149b-8919-4eea-89d2-4be800c22af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>50d9f922-7752-4895-b4a3-0f06b756d5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-4g3mytlyz8-zip&quot;)</value>
      <webElementGuid>0734a8b1-9e1f-4493-84bc-b64af1aa0b55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-4g3mytlyz8-zip']</value>
      <webElementGuid>deaa4bcf-44dd-4289-98d8-7a7f559d02ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div[3]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>b82cb914-f2ec-473e-8a60-0d7075556d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>875a6b74-745b-4b78-9a7b-f7caa49b6e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address-4g3mytlyz8-zip' and @type = 'text' and @placeholder = 'Zip']</value>
      <webElementGuid>13a8ed07-5a4e-41cb-9b05-0b60a7864f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
