<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_length (in feet)_length</name>
   <tag></tag>
   <elementGuidId>05b09c6c-fcda-4a2a-9cef-9883dc5c3ef7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#length</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='length']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>814e45c9-22fc-4039-bc12-8404d18b46c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>length</value>
      <webElementGuid>329c49a0-5e95-4ce1-b168-586aac02d945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e5ce4e0-ae8d-4350-a7d0-a8906b638926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>a2b204cd-33bf-478c-8711-83de0957a79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3454617a-31e6-4466-9dd5-2a32667cc6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>52139ff9-0e8c-496a-9420-be83f90c1e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>length_1440013438</value>
      <webElementGuid>5c5b4319-8168-47c5-ad41-7e81bc8c354d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4b10046c-8880-4cb2-9848-987cf497749c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>08e020a2-335c-4447-9d84-5e7074526734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;length&quot;)</value>
      <webElementGuid>3249c9ea-55a2-4f94-bb0c-8e5321f08801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='length']</value>
      <webElementGuid>24c967f0-2c39-4000-a6db-df0be2ab3acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[4]/div/div/div/div/div[2]/div/div[2]/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>82f96249-1dd6-43c0-a226-1343ba294585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>de51d90f-7f2f-4c53-b75f-95ca2bf043fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'length' and @type = 'text' and @placeholder = '20']</value>
      <webElementGuid>de9048ab-476b-4ea9-8c5c-69ecdfe4e2c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
