<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Other Policy Type_otherTypeOfPolicy</name>
   <tag></tag>
   <elementGuidId>dd4469e0-1bf4-4eab-b0fb-0323876a5364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otherTypeOfPolicy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherTypeOfPolicy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c916d43-526e-4847-b071-866f0d7d1a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherTypeOfPolicy</value>
      <webElementGuid>bfffabec-c6df-4d3c-9a20-b22f1bde78da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9118650d-135a-46a3-8f3f-8bef14979e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input PolicyDetailsForm_control2__2nDnB</value>
      <webElementGuid>c11a6a33-fd78-4305-bc94-f3c196b98766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>17f79137-d732-4a39-acc7-902a5469c007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9a6456c2-a535-44a1-9d02-04c511dafb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>otherTypeOfPolicy_1440013438</value>
      <webElementGuid>60e4b824-fa42-4671-a7a7-07c33a90f39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Other Policy Type</value>
      <webElementGuid>01a457f7-645d-47ea-ae6e-e63e5293665b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Other Policy Type</value>
      <webElementGuid>f1d29380-55f4-40b1-b9f6-f68c359fbecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherTypeOfPolicy&quot;)</value>
      <webElementGuid>4ab715f4-4064-4278-8782-7f948d49fba7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherTypeOfPolicy']</value>
      <webElementGuid>e4a2cdcc-56c2-42c6-97c5-17c2940a9cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>493036c7-d9d2-4383-b503-964c7af264d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>c29112dc-9908-416c-91d3-9e87dd557026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otherTypeOfPolicy' and @type = 'text' and @placeholder = 'Other Policy Type']</value>
      <webElementGuid>5152057d-6d9b-4ce8-86f5-d680c453acd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
