<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ohio</name>
   <tag></tag>
   <elementGuidId>bc1ae638-7c88-45d1-aedc-3b29736a01ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-5-option-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-5-option-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8eb280c2-7827-4d64-ae61-9ca676ef4138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicGenericSelectControl__option jut__GenericSelectControl__option jut__GenericSelectControl__optionFocused css-1n7v3ny-option</value>
      <webElementGuid>9baa257f-1391-44f4-af2d-038a1267b695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-5-option-4</value>
      <webElementGuid>c7682915-ef1b-4e22-a495-bd3f0deacad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ee58e8be-c230-41c5-acb9-86352e06376d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ohio</value>
      <webElementGuid>a6a21077-8386-4371-bd54-0f2f0d0358ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-5-option-4&quot;)</value>
      <webElementGuid>cb56cb5d-c7b9-4a89-b84f-44b7fa63b4f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-5-option-4']</value>
      <webElementGuid>0aaa927b-fd12-4428-96d0-021ad8656af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Michigan'])[2]/following::div[1]</value>
      <webElementGuid>f7256dc4-d484-4157-b5ea-8767926188bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iowa'])[1]/following::div[2]</value>
      <webElementGuid>b67c00ef-ba4b-4238-96a9-1e58837c1439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wisconsin'])[1]/preceding::div[1]</value>
      <webElementGuid>c352dc5b-e55c-4d8b-b914-1868a0afabf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ohio']/parent::*</value>
      <webElementGuid>81d1762c-1f27-4e32-8792-3c8c2dca9098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[5]</value>
      <webElementGuid>226440e8-e366-43d8-bd04-2fb405b548b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-5-option-4' and (text() = 'Ohio' or . = 'Ohio')]</value>
      <webElementGuid>6995387b-8328-4234-9deb-a60152531d14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
