<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_expirationDate</name>
   <tag></tag>
   <elementGuidId>71121601-68d9-45d7-b656-52d4dacb6d25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expirationDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expirationDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd984b89-bc5f-411c-b87a-a21436e441a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6ce59b0e-7f50-4d22-b8e6-40a52dee537e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expirationDate</value>
      <webElementGuid>02836b2e-5be6-4389-a0c2-897c57e49cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>06/01/2023</value>
      <webElementGuid>2a8a9f2f-5a62-4897-8968-a72fcfbb4fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d345c83d-3ac3-417b-9043-cff0ff2e66dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicDatePickerField__datePicker jut__DatePickerField__datePicker</value>
      <webElementGuid>62c5e967-227f-4431-8e1b-0a299ebb906a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expirationDate&quot;)</value>
      <webElementGuid>3377cc9f-434b-4c7e-bc63-090f8243875d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expirationDate']</value>
      <webElementGuid>098402fe-598a-4bd0-abbd-8e1c8959dd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[5]/div/div/div/div/div/div[2]/div/div[2]/div/div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>60a11edc-2899-4f05-a10b-47f8f6c7e7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>9dcb6754-0773-4e5f-ba17-c4a6f9ac5f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expirationDate' and @placeholder = '06/01/2023']</value>
      <webElementGuid>ed26e101-16ec-4740-a7de-442c4b1abde8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
