<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Effective Date_effectiveDate</name>
   <tag></tag>
   <elementGuidId>890265b7-349f-4f9d-a52b-e90aa9b14e19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#effectiveDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='effectiveDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>300901be-e80c-45f1-99bd-815683993f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>067e20d2-7abf-4f96-a07f-49e18eca0843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>effectiveDate</value>
      <webElementGuid>e0ed4e4f-24a3-4414-aff4-6cdba262d14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>06/01/2023</value>
      <webElementGuid>56f0dc1a-574b-4120-bd09-0163388f8e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e1f0ed22-7327-42c1-81dc-bbe480780d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicDatePickerField__datePicker jut__DatePickerField__datePicker</value>
      <webElementGuid>c8bbeb78-2504-419a-95d4-094856b127d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;effectiveDate&quot;)</value>
      <webElementGuid>a6350b45-0e8e-4e69-a54e-e4c0f6225cb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='effectiveDate']</value>
      <webElementGuid>973babe8-33cc-48b1-b505-9a407bfeba3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[5]/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>3562698f-70a4-489d-b568-c456431716cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>617eb15d-52e8-4449-80ca-c7144c395af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'effectiveDate' and @placeholder = '06/01/2023']</value>
      <webElementGuid>46c2a903-d8fa-484d-9071-4c9ace5828c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
