<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Driver License number</name>
   <tag></tag>
   <elementGuidId>6609dc76-0ebc-4992-925e-33e7245f5596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='driversLicenseNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#driversLicenseNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e5a58e3-f475-447f-a18b-ece0359a076f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>driversLicenseNumber</value>
      <webElementGuid>56304b88-b56b-4e25-8aba-a5d7d6fd28b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd07bfd0-e2f3-4528-a3de-eb9e56a8eb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>cbabef6f-7b04-4951-aad7-c7153594a6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>99f62b3d-e675-4466-b533-3bb14007bc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1729e304-6918-4fc0-b20e-a35dadb3783b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>driversLicenseNumber_1440013438</value>
      <webElementGuid>0684f104-ba29-4874-81b1-d07e892418c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Driver's License #</value>
      <webElementGuid>24cace36-37c6-45ed-99e0-bd73b56dd14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Driver's License #</value>
      <webElementGuid>ac81d37b-1f27-4497-9f96-8b4b28770d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;driversLicenseNumber&quot;)</value>
      <webElementGuid>9c2cce6d-f03b-48fd-aba4-ffcf0e5b3cda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='driversLicenseNumber']</value>
      <webElementGuid>c034548a-9bd2-463f-b478-30e3217f2bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[5]/div[2]/div/div/div/div[2]/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>b7df6b1a-3e5a-41bb-9eb2-fd42a2387148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>0a0f26be-7d90-4bdf-a2f6-d86f035ce328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'driversLicenseNumber' and @type = 'text' and @placeholder = concat(&quot;Driver&quot; , &quot;'&quot; , &quot;s License #&quot;)]</value>
      <webElementGuid>94ac904c-00f2-4e82-96a3-4ab691189fd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
