<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Accept</name>
   <tag></tag>
   <elementGuidId>4dff158f-2461-4f8b-b605-6f3a519dde91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='includeUmUim']/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#includeUmUim > div.dynamicRadioButton__radioButton.jut__RadioButton__radioButton > label.jut__RadioButton__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8c12df72-534b-4871-a5d4-6686c7ef9054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>includeUmUim_Accept</value>
      <webElementGuid>8abc8ea0-3d00-410d-8ede-671f35e0a19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ea82e9b0-0ddc-4f6e-9310-3f49f38edcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__RadioButton__label</value>
      <webElementGuid>ca7a75eb-2022-43e9-966e-64bf7f9a88e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>96c37f16-a789-4cfc-bf06-a6df7cf450d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;includeUmUim&quot;)/div[@class=&quot;dynamicRadioButton__radioButton jut__RadioButton__radioButton&quot;]/label[@class=&quot;jut__RadioButton__label&quot;]</value>
      <webElementGuid>911e185f-ccb8-483f-b704-eafabb6ee369</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='includeUmUim']/div/label</value>
      <webElementGuid>e788e3f9-3f87-4963-9dc4-0235f3284df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include UM / UIM Coverage?'])[1]/following::label[1]</value>
      <webElementGuid>bfce5e55-bb4d-432b-bb78-48886ddda69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autos'])[1]/following::label[2]</value>
      <webElementGuid>19dda927-f36d-4b7e-bf70-65106b158b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/preceding::label[1]</value>
      <webElementGuid>b35d7493-ef7a-427a-9b50-0e835adffa19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/label</value>
      <webElementGuid>fe2e34e1-3e69-4e42-8df3-d3d3fc182856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>cadc4a95-0965-4ddb-88e0-aa4d656d54e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
