<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Account_baConfirm</name>
   <tag></tag>
   <elementGuidId>15e59548-3f94-48dc-9477-98c1edebaf39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#baConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='baConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b695255b-c62d-4a14-a2b8-9b3a8764b14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>baConfirm</value>
      <webElementGuid>66a3c5f2-bffd-4294-8f92-9c3125d8246f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4dbe63cb-8581-49b9-ad82-5bd53feb28e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>dc79067c-9fc6-47a2-b4b4-def48696efa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>53ebb688-5f3a-4c44-a835-1a2a014c29b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>66323f9d-5335-4c48-b8fa-af325ff2f61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c7322345-5b31-441e-b069-f03c1026be47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>baConfirm_1440013438</value>
      <webElementGuid>120558bc-2933-462b-a42e-a17a6bb81734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>4-17 digit account #</value>
      <webElementGuid>34d7b2c1-3b02-471e-9b99-2329c369ef0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>4-17 digit account #</value>
      <webElementGuid>5446fff9-0bcd-4a3c-a32a-8a50dd94231f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;baConfirm&quot;)</value>
      <webElementGuid>0b4d0a5b-5bf2-44da-9154-7da520a405fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='baConfirm']</value>
      <webElementGuid>7547aebf-66cd-4522-b131-0886dd8416c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bankAccountGrid']/div[4]/div/div[2]/input</value>
      <webElementGuid>d63ffdc1-4d17-4309-9f28-09cb67640472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>aa949828-2714-486f-acb2-4338f07a1c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'baConfirm' and @type = 'text' and @placeholder = '4-17 digit account #']</value>
      <webElementGuid>9aeaf8f8-1dea-4823-981e-647efcb4daa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
