<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account_baAccountNumber</name>
   <tag></tag>
   <elementGuidId>ee26a3e5-bd61-4525-b31f-c13cdf240a19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#baAccountNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='baAccountNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>374ad77f-4321-49ac-a94b-24aa4de63059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>baAccountNumber</value>
      <webElementGuid>2dffadfc-3698-4bba-b0c9-8a843e9c7325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbd5e1e8-f971-41ee-a622-586ea52c8bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>788be9d1-ff07-4a78-979a-f4093d67070a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>7e320221-e19d-4321-89f8-88cd2ca464c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4b9e5b69-91e5-4b3a-ab61-978af444b0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>368b55a6-1cd3-4329-8dd9-d0cc5192aa5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>baAccountNumber_1440013438</value>
      <webElementGuid>ab1380fb-40b0-4642-839b-ba4a13fecda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>4-17 digit account #</value>
      <webElementGuid>f8f11695-f323-4c87-860b-04ab9c9e266b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>4-17 digit account #</value>
      <webElementGuid>49febae6-3a16-440d-be7c-a71efafff76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;baAccountNumber&quot;)</value>
      <webElementGuid>65307e10-1cf7-41a6-9204-1aa517202c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='baAccountNumber']</value>
      <webElementGuid>2e776472-8248-4f2f-b55d-26d215a09ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bankAccountGrid']/div[3]/div/div[2]/input</value>
      <webElementGuid>44148b79-1572-48f5-a981-274257369c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>e1e38dc9-7b26-41d8-b6d1-b738cd05bfb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'baAccountNumber' and @type = 'text' and @placeholder = '4-17 digit account #']</value>
      <webElementGuid>e3ad84d1-1a80-4012-8680-85c0e219e611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
