<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Start a New Business</name>
   <tag></tag>
   <elementGuidId>1812e92d-fec3-4c84-9ff8-4e2e8fffb93e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainContainer']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-tile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4bbc6505-e416-4361-98f5-6732895c516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-tile</value>
      <webElementGuid>173d022e-0e0b-42db-be3f-e528b867dc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start a New Business</value>
      <webElementGuid>79a79051-071c-49f8-a7bd-03f238578f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContainer&quot;)/div[@class=&quot;gw-tiles gw-tiles-large&quot;]/div[@class=&quot;gw-tiles-aligner&quot;]/div[@class=&quot;gw-tile&quot;]</value>
      <webElementGuid>0abd6196-16a2-40d2-a78c-09ab0e142e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContainer']/div/div/div</value>
      <webElementGuid>8ed6b34f-c256-4370-8970-0b09da3578dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Business Dashboard'])[1]/following::div[2]</value>
      <webElementGuid>e99cf833-668d-47b1-8323-69d3b4f21e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HELP'])[4]/following::div[10]</value>
      <webElementGuid>7d4c5cc6-fb98-4ab8-b02e-64f649d9c259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Quotes'])[1]/preceding::div[5]</value>
      <webElementGuid>f1c0b88b-0812-4f1f-8023-02a4b65e8169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>cb3e3483-bd33-4570-a418-7f7182e25ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Start a New Business' or . = 'Start a New Business')]</value>
      <webElementGuid>566e5f61-20e5-44cb-8426-7703af62e590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
