<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Address TypeHomeAddressAddress 2Address_5994e5</name>
   <tag></tag>
   <elementGuidId>2372e8c2-78a1-4819-a4d0-9efdc010b091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > div.ContactForm_gridrow__1pOGG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>580b7b0e-127f-4ef8-9af7-71642ac67eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ContactForm_gridrow__1pOGG</value>
      <webElementGuid>ddd12216-78b8-477c-96f1-34ad87246353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*Address TypeHome*AddressAddress 2Address 3*City*StateState*ZIP Code</value>
      <webElementGuid>abd0ff08-047b-4d44-87be-70e81544140f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;PageContainer_standard__3bPCs&quot;]/div[@class=&quot;QuoteWizard_container__3EESf&quot;]/div[1]/div[@class=&quot;Wizard_bottomContainer__3lWO5&quot;]/div[2]/div[1]/div[@class=&quot;WizardPanel_body__21TLo&quot;]/div[1]/div[1]/div[@class=&quot;CreateUpdateView_formContainer__XCC_-&quot;]/div[@class=&quot;FieldSet_container__3odpU&quot;]/div[1]/div[3]/div[@class=&quot;ContactForm_gridrow__1pOGG&quot;]</value>
      <webElementGuid>16259aff-9273-4280-99c0-7a4198b35fe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div</value>
      <webElementGuid>6da085e2-63a8-4621-9a3d-d63ec6577a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::div[4]</value>
      <webElementGuid>cccc2a4c-5ea8-4ac8-bbb3-cc930e7a82b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle Name'])[1]/following::div[8]</value>
      <webElementGuid>eef67851-5000-4db7-ac27-83baee875fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[3]/div</value>
      <webElementGuid>4daae043-927d-4726-8758-9ca6d7e4c82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '*Address TypeHome*AddressAddress 2Address 3*City*StateState*ZIP Code' or . = '*Address TypeHome*AddressAddress 2Address 3*City*StateState*ZIP Code')]</value>
      <webElementGuid>486ab0f7-aa46-4a2d-91d9-ae121be8987d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
