<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0081-CaCarpc 020590081CandiCarpcan</name>
   <tag></tag>
   <elementGuidId>7acf73c3-4527-4112-a6e9-0ac363d65a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-8-option-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-8-option-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb179312-ac18-4b83-8557-81884c36ea73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicGenericSelectControl__option jut__GenericSelectControl__option jut__GenericSelectControl__optionFocused css-1n7v3ny-option</value>
      <webElementGuid>df68afac-02a5-4f6b-8f1c-ded0df9734c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-8-option-6</value>
      <webElementGuid>77a44e55-ddea-4c1c-8ab5-996248422c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>61ac2364-1386-4021-b77d-520ca6634f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0081-CaCarpc 020590081CandiCarpcan</value>
      <webElementGuid>18d4c126-60bb-4082-a25b-9e2e7d0682da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-8-option-6&quot;)</value>
      <webElementGuid>e6f836e6-17e5-4bec-8d5e-49a2d75115ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-8-option-6']</value>
      <webElementGuid>cf2c10c9-04a5-4a5e-a776-d1aad4029ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[2]/following::div[6]</value>
      <webElementGuid>ccb55cec-1966-45ba-90ab-7dd5ba31b7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'react-select-8-option-6', '&quot;', ')')])[1]/following::div[10]</value>
      <webElementGuid>d26e2939-0fb1-4c21-9a40-64ec2b8cb177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0081-CaCarpc 020590081CandiCarpcan']/parent::*</value>
      <webElementGuid>35e62a18-7ecb-4aa4-ab57-a9b19258eaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>95eb8e53-1d00-4dc3-8a72-32045d0d8e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-8-option-6' and (text() = '0081-CaCarpc 020590081CandiCarpcan' or . = '0081-CaCarpc 020590081CandiCarpcan')]</value>
      <webElementGuid>68afdc70-ffc1-472b-8cbe-b373d5fc95da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
