<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_zipCode</name>
   <tag></tag>
   <elementGuidId>ca082886-c641-4dcc-a257-42f7c0fc9227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c1b80c9-caf7-4011-bfc3-99fe73f299c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zipCode</value>
      <webElementGuid>e596177b-47e8-4b5c-8851-8aadca08a616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e09ff577-42e3-4de8-8582-ce175f80fc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>e2c592c4-ebcf-4861-bfab-7263384d9d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f73e0479-900b-41df-93bd-e29dc4a92130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>10b01990-b1b9-4aaf-87b1-ede97dcc0b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>zipCode_1440013438</value>
      <webElementGuid>c59e45ee-fe6e-44c0-a84c-d9d4208bbfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ZIP</value>
      <webElementGuid>794bbb7f-af3b-49a0-97f9-470c0cc5ed09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ZIP</value>
      <webElementGuid>51e8ee67-2cb7-4ec4-9d27-5045e7c1a61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zipCode&quot;)</value>
      <webElementGuid>5ce801bd-c2a0-4b55-8180-98511f1d9810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zipCode']</value>
      <webElementGuid>670ff881-403c-493a-b616-a907cf3a8525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>73861820-00b0-4262-afc6-c7cca591462a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>4c7abe79-b340-4c15-916b-da667c8695c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zipCode' and @type = 'text' and @placeholder = 'ZIP']</value>
      <webElementGuid>d9a0c1c8-b8c1-44d6-8360-07e80022aca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
