<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_contact-xbqthne5gh-address-oah9g_435d5b</name>
   <tag></tag>
   <elementGuidId>2877d8a9-5d07-4611-9fa0-ef5a9e7424d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-xbqthne5gh-address-oah9g16zhhj-city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact-xbqthne5gh-address-oah9g16zhhj-city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ddc0b75-dac1-47c4-b1c9-c0a7aa760cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-xbqthne5gh-address-oah9g16zhhj-city</value>
      <webElementGuid>047eb37f-78d5-4b8b-ab27-776cd28f9486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca34377c-c74b-4e27-a1bb-0197d065011b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>9b2f9c32-3ae0-498c-9c7a-482eccf27d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-contact-xbqthne5gh-address-oah9g16zhhj disabled-address-level2</value>
      <webElementGuid>ca4d74da-1d1e-4795-bd41-bed0d867b787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d2998349-ce44-4914-887d-9f84236aff92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>contact-xbqthne5gh-address-oah9g16zhhj-city_1440013438</value>
      <webElementGuid>9a5d1791-3aa7-47c6-9b40-3b23ca859e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>a116336c-2cc7-4f94-bb58-f6a220af8232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>228ec6b0-3f49-46f0-9954-4352af1b415b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-xbqthne5gh-address-oah9g16zhhj-city&quot;)</value>
      <webElementGuid>fd5a36a7-1bc1-49c5-8d38-17b68e880e28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact-xbqthne5gh-address-oah9g16zhhj-city']</value>
      <webElementGuid>5994005c-cc1f-4b01-999c-39469a226a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div/div/div/div/div[5]/div/div/div/div[2]/input</value>
      <webElementGuid>89c97fe7-81e1-4876-891c-260a9a5cba4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/input</value>
      <webElementGuid>2de62e65-6ca0-4af3-ade4-46e91100e521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact-xbqthne5gh-address-oah9g16zhhj-city' and @type = 'text' and @placeholder = 'City']</value>
      <webElementGuid>6815ee87-a208-4cc5-b223-2f1be7c16fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
