<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZIP Code_contact-xbqthne5gh-address-o_7d6b37</name>
   <tag></tag>
   <elementGuidId>d263263d-84e6-4ae1-8346-a1edd1fa66ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-xbqthne5gh-address-oah9g16zhhj-zip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact-xbqthne5gh-address-oah9g16zhhj-zip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b229e416-eba0-40f9-a92a-77f61d6b4abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-xbqthne5gh-address-oah9g16zhhj-zip</value>
      <webElementGuid>e80019e4-b678-4436-86bc-7c460e85cf47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0e42d71-23c4-4b9e-8eaa-ba835f7215d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>0b7144ef-42aa-4608-beee-82465c8e766b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-contact-xbqthne5gh-address-oah9g16zhhj disabled-postal-code</value>
      <webElementGuid>637d0cf3-321f-4513-bbed-cb667b8246f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e18f2bdd-3e5f-4712-bce5-111178b957c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>contact-xbqthne5gh-address-oah9g16zhhj-zip_1440013438</value>
      <webElementGuid>88ba13e7-fcf3-49ef-a147-fbf86b613e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>e4e5c759-5fec-430e-afd7-26e578763f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>29b7ffa2-dd67-4ce2-8250-4f9ce38ab2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>49503</value>
      <webElementGuid>d95ef260-1d65-471c-a7df-7f8e0cd7d7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-xbqthne5gh-address-oah9g16zhhj-zip&quot;)</value>
      <webElementGuid>198d2a45-1c57-4282-aa16-0795ed48b094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact-xbqthne5gh-address-oah9g16zhhj-zip']</value>
      <webElementGuid>be5d057c-7dea-4a82-9ee0-e13e831ae7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div/div/div/div/div[5]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>24ea4d35-be46-4ce1-9037-6548da23e283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>5359972a-2b14-4921-99c7-72d1841ba803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact-xbqthne5gh-address-oah9g16zhhj-zip' and @type = 'text' and @placeholder = 'Zip']</value>
      <webElementGuid>6c8d9079-ddb5-4ca2-adf1-c7b982349c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
