<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_AccInfo_TextBox_Address (1)</name>
   <tag></tag>
   <elementGuidId>7e942dcc-4060-46c5-bac5-86eba86deccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'addressTypeAhead_contact')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9d2892c-57ee-4be6-a6b8-9d015b0ad012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI</value>
      <webElementGuid>e3feeef7-8e1a-406e-8e99-dcd7bad654ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91071a2e-38cd-4503-a576-7e8f2081fbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>cebd4336-01b5-4833-b1f8-417334d4213c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-contact-jp0dhqd1yn-address-7b9nflk4845 address-line1</value>
      <webElementGuid>fab3c73b-5554-4f9c-90ea-235ceeb21660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3bc1bd9a-165a-44e1-9029-e76786c485ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI_1440013438</value>
      <webElementGuid>b6031903-1e3c-44b7-bdff-379b6b4482f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>df35f429-3573-4aca-89f7-0971818cf6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>0f9afff1-16c8-48ac-aaf4-f3e875b7aff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI&quot;)</value>
      <webElementGuid>14ad053d-84d2-48dd-b4a9-8358a0d35132</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI']</value>
      <webElementGuid>c0e395c7-8b00-49cf-aa53-020a7108df8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>39a4f1f6-d3f8-4499-990d-96efe93512d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>39f003a0-5bb6-4a31-9580-26f976b878f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI' and @type = 'text' and @placeholder = 'Street address']</value>
      <webElementGuid>14e6018f-21a1-4307-968d-f1e416dc2d10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
