<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_Accinfo</name>
   <tag></tag>
   <elementGuidId>45ec2bca-befd-44bd-8518-649e90846e8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-akbvzphuy89-emailAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact-akbvzphuy89-emailAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87628320-12c5-4b3e-8e47-0ab7756e7474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-akbvzphuy89-emailAddress</value>
      <webElementGuid>21f73322-e6a5-47b8-ad52-a639358a0181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e70c208-cd0f-4eef-8ffd-12d1ffb907a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>f3f8b605-5630-47c5-ae1f-d6b3f2dd0940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3a410cd9-3954-4e2b-ba63-e069ed7fda4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34b1cecf-35c2-4b38-92b9-0e2e89d65a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>contact-akbvzphuy89-emailAddress_1440013438</value>
      <webElementGuid>ac637a9e-65ae-4531-9b64-400b0bea0ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>rsmith@hastingsmutual.com</value>
      <webElementGuid>0a326dca-478c-4944-8faf-62334fc7d268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>rsmith@hastingsmutual.com</value>
      <webElementGuid>253fe391-71a4-4d93-abeb-48c69be287c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-akbvzphuy89-emailAddress&quot;)</value>
      <webElementGuid>74d6354f-f83b-4fca-9dc1-b32abb3ae80f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact-akbvzphuy89-emailAddress']</value>
      <webElementGuid>a0e47c2b-c87e-4990-9f92-72006b3248be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>bdb95f68-a322-4e12-bd40-87166ed3a23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/input</value>
      <webElementGuid>f5e7ed67-ccb9-4331-93e4-04411c8f004d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact-akbvzphuy89-emailAddress' and @type = 'text' and @placeholder = 'rsmith@hastingsmutual.com']</value>
      <webElementGuid>a33d0dcc-20c9-4f7b-a3f4-acaacfb642cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
