<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birth Date_birthDate</name>
   <tag></tag>
   <elementGuidId>cbd345cf-f3de-47fd-94ce-f5eb8a331da8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#birthDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3897853f-230d-4771-ae01-1ef77385a19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e4a4df6e-ad35-4243-ab76-7f85879b23e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthDate</value>
      <webElementGuid>0e3fc6fd-f62a-4f5f-889e-2bbd68ddc266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Birth Date</value>
      <webElementGuid>117534ac-488d-4e3a-ad7d-30f2a62d1cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>83d43adb-ca57-4b26-b0c7-5798e6ad6a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicDatePickerField__datePicker jut__DatePickerField__datePicker jut__InputField__inputSmall</value>
      <webElementGuid>de9e288c-fb67-4217-8376-fbc6efad47ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthDate&quot;)</value>
      <webElementGuid>4c73649f-add5-4a51-b637-284b6ce03ffe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthDate']</value>
      <webElementGuid>dd482b24-5a7b-4c55-9ca0-57414bb79b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[5]/div[2]/div/div/div/div[2]/div/div[2]/div/div/div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>f62fee42-568e-44f9-b2a1-6082b1652c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>cfd084e8-ac91-4121-b9a4-ee73dc85e1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'birthDate' and @placeholder = 'Birth Date']</value>
      <webElementGuid>73da7d16-3041-45b9-82fa-b5b432ac72be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
