<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZIP Code_address-ttvec7qugrt-zip</name>
   <tag></tag>
   <elementGuidId>1d15655e-0a03-4635-aba9-03a87fc0d2fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-ttvec7qugrt-zip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-ttvec7qugrt-zip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a88ec93-3a15-4c26-ae50-9eca0662e14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ttvec7qugrt-zip</value>
      <webElementGuid>639f4e51-6887-4a78-8b59-3239220c2a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7405422e-b383-497f-9679-604a720655f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>89127d9f-e81a-437f-a93f-70b7485760b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-address-ttvec7qugrt disabled-postal-code</value>
      <webElementGuid>db09b455-9bcc-4f86-8322-25beb9f769fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>81509ae3-077e-462a-933d-3aa12e0e4ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>address-ttvec7qugrt-zip_1440013438</value>
      <webElementGuid>092403cf-274e-4dff-87cd-3770b93ebf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>fae097fd-2f1d-4046-a8df-0a3adc2e7712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>bdca3962-de51-4d75-9a67-671104ebdc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ttvec7qugrt-zip&quot;)</value>
      <webElementGuid>d497ab0f-ac17-4440-9a4e-a5541783fbb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-ttvec7qugrt-zip']</value>
      <webElementGuid>53a047fa-eda8-48f2-87f1-2244272eb3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div/div[3]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>7d2e6dd1-c1bc-49cc-96aa-4965dbab6b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>7f54f793-dd98-4f92-b9bf-440628d40a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address-ttvec7qugrt-zip' and @type = 'text' and @placeholder = 'Zip']</value>
      <webElementGuid>6d576980-f575-40fc-8436-7e0e9f526287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
