<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Michigan Street Northwest, Grand Rapids,_d97d70</name>
   <tag></tag>
   <elementGuidId>e2acf1d9-5b17-486a-bf73-669f60b9b47a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='addressTypeAhead_address-ttvec7qugrt-googleAddressAPI_typeaheadDropdownList']/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>016e331b-f355-4c7b-8cde-daeae1337d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bb8a5fb4-cac2-4943-98af-5182e4ebef76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b169a94-add1-45ab-99f5-070decd7868b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR</value>
      <webElementGuid>26596287-9bf9-43c1-b533-481b9631f684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Michigan Street Northwest, Grand Rapids, MI, USA</value>
      <webElementGuid>75096393-5bf0-4a14-998f-5f7ed8097521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_address-ttvec7qugrt-googleAddressAPI_typeaheadDropdownList&quot;)/li[@class=&quot;AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR&quot;]</value>
      <webElementGuid>62215540-f728-4bcf-9ab5-97e20cc75c81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='addressTypeAhead_address-ttvec7qugrt-googleAddressAPI_typeaheadDropdownList']/li[3]</value>
      <webElementGuid>f4e4c65d-e9e3-48ce-9291-358cf080a04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Michigan Street Northeast, Grand Rapids, MI, USA'])[1]/following::li[1]</value>
      <webElementGuid>e6b48065-88b7-489a-a859-03e7115fb36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Michigan 6, Grand Rapids, MI, USA'])[1]/following::li[2]</value>
      <webElementGuid>c222788a-3763-4d89-97a1-6c0e11ee69bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Michigan Avenue, Chicago, IL, USA'])[1]/preceding::li[1]</value>
      <webElementGuid>1339d610-dd18-47d8-ab56-e8b12c507955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Michigan Place Northeast, Grand Rapids, MI, USA'])[1]/preceding::li[2]</value>
      <webElementGuid>6b55f039-9313-46ab-baf3-ae194a0ac4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Michigan Street Northwest, Grand Rapids, MI, USA']/parent::*</value>
      <webElementGuid>17d0c08e-2001-4320-becf-be9dc27fa2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>c957bfc4-8a1b-4b18-a916-904fda6c288e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Michigan Street Northwest, Grand Rapids, MI, USA' or . = 'Michigan Street Northwest, Grand Rapids, MI, USA')]</value>
      <webElementGuid>60478bd3-6d52-48db-8882-a32d7d41f496</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
