<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create New Account</name>
   <tag></tag>
   <elementGuidId>4a77010b-6823-4fdf-b9a5-d2ef4bf392e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='create']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>545b47b0-32b4-4f17-8bd6-9ab528530816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10c4f0e5-7d7b-4767-80c7-7599f89af228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicButton__button jut__Button__button jut__Button__primary jut__Button__large</value>
      <webElementGuid>cec4eb1c-6470-4aea-8d04-c6e6b4d3add9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create</value>
      <webElementGuid>ae88b911-c40e-418d-a18a-93f904386369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Account</value>
      <webElementGuid>e276224a-ec67-4cf4-b6aa-3d9856d9a31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create&quot;)</value>
      <webElementGuid>0503b6b6-2590-4e25-b9c7-cd6862f137fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='create']</value>
      <webElementGuid>6ddceb2d-06cf-46c7-af44-aad19f82ebe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[3]/button[2]</value>
      <webElementGuid>2521cd30-5a88-436c-8e02-52c09ca65ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[1]</value>
      <webElementGuid>a79bcca6-6fe7-45ba-ab5e-d3b9715f0625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code'])[1]/following::button[2]</value>
      <webElementGuid>36cb7239-a089-4097-9eb3-519860c0e511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'create', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>a67fd9df-0bf1-4214-9c62-2c0e76abf5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>c9c77a5f-8f9c-4a6a-b441-42f8bebee294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'create' and (text() = 'Create New Account' or . = 'Create New Account')]</value>
      <webElementGuid>68f5699d-ea70-4d76-96bf-73fa75c27ea7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
