<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continue</name>
   <tag></tag>
   <elementGuidId>a7657a82-364e-4483-9428-0692712eb048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.dynamicButton__button.jut__Button__button.jut__Button__primary.colorAccent > span > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fb2b2872-98f0-4b42-b627-e87ac99bbea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>c4ae8df9-3c6f-46b1-b1bc-dfeb31b1afcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;gw-branding-agencyportal&quot;]/body[@class=&quot;themeRoot dynamicRoot ReactModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open jut__ModalNext__overlay&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open dynamicModal__modal jut__ModalNext__modal StandardizeAddressModal_standardizeAddressModal__2ZOci&quot;]/div[@class=&quot;jut__Grid__grid jut__Grid__vgapNone jut__Grid__hgapMedium&quot;]/div[@class=&quot;jut__ModalFooter__modalFooter&quot;]/div[@class=&quot;jut__Flex__gwFlex jut__Flex__gwGapMedium jut__Flex__gwAlignItemsCenter jut__Flex__gwJustifyContentEnd jut__Flex__gwReverseWrap jut__Flex__gwDirectionRow jut__ModalFooter__modalFooterFlexLayout&quot;]/div[@class=&quot;StandardizeAddressModal_footer__2L-uc&quot;]/button[@class=&quot;dynamicButton__button jut__Button__button jut__Button__primary colorAccent&quot;]/span[1]/span[1]</value>
      <webElementGuid>9584b83c-277a-4900-91d4-9719c49e9e79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::span[2]</value>
      <webElementGuid>6cc11b91-4f7a-4464-9e3a-bf5e160e07c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='michigan, Grand Rapids, MI 49503'])[1]/following::span[4]</value>
      <webElementGuid>24813e8c-8c50-45bf-a65f-74206344ed41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>8bbab3a8-6811-49ae-a036-848dd086e888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]/span/span</value>
      <webElementGuid>4263fece-9a3d-4a31-916a-825526c71b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>7be13b3f-5541-4b7e-8abe-f8bdf3fb6f72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
