<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Contact TypeCompanyContact RoleBoth</name>
   <tag></tag>
   <elementGuidId>5a7cb142-f0d0-4cd0-8472-6f92932e4f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div[2]/div/div[2]/div[2]/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ca98b725-3896-4a8e-a735-70276fd9d9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ContactForm_gridrow__1pOGG</value>
      <webElementGuid>7bf7d1f8-7021-4247-83f5-eddf397e09f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*Contact TypeCompany*Contact RoleBoth</value>
      <webElementGuid>c8e98371-75c3-4c69-98c3-df8166029931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;PageContainer_standard__3bPCs&quot;]/div[@class=&quot;QuoteWizard_container__3EESf&quot;]/div[1]/div[@class=&quot;Wizard_bottomContainer__3lWO5&quot;]/div[2]/div[1]/div[@class=&quot;WizardPanel_body__21TLo&quot;]/div[1]/div[@class=&quot;AdditionalInfo_section__17Hm0&quot;]/div[2]/div[@class=&quot;FieldSet_container__3odpU&quot;]/div[2]/div[@class=&quot;InputList_editMode__3LmDi InputList_editContainer__1i18K&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;ContactForm_gridrow__1pOGG&quot;]</value>
      <webElementGuid>b3177669-ffd7-461f-8775-b02ec46f9f06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div[2]/div/div[2]/div[2]/div/div/div[2]/div</value>
      <webElementGuid>c794f232-fd04-4afd-8f80-4212592a7e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Company'])[2]/following::div[8]</value>
      <webElementGuid>e0022a1b-69fd-4546-96e0-57a58b08ef4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search For An Existing Contact'])[1]/following::div[14]</value>
      <webElementGuid>ae0d6dc4-6c39-47cc-af80-67353fbb0570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div</value>
      <webElementGuid>d6e2cd6b-4986-4c28-a4ea-90eca0c5ecbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '*Contact TypeCompany*Contact RoleBoth' or . = '*Contact TypeCompany*Contact RoleBoth')]</value>
      <webElementGuid>05f166b7-315b-41d6-87d8-2247d614b025</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
