<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email AddressPhone NumberValue entered _928e06</name>
   <tag></tag>
   <elementGuidId>8c71acf3-8f0b-4fef-811e-ebe94f28005f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div[2]/div/div[2]/div[2]/div/div/div[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b896ac60-da8d-4ffb-b563-a9b6eddba75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ContactForm_gridrow__1pOGG</value>
      <webElementGuid>69884736-36bb-47e3-bba4-a288b643478d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email Address*Phone NumberValue entered must be a valid phone number</value>
      <webElementGuid>efe658fd-29c8-44e1-872c-7500fbda63cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;PageContainer_standard__3bPCs&quot;]/div[@class=&quot;QuoteWizard_container__3EESf&quot;]/div[1]/div[@class=&quot;Wizard_bottomContainer__3lWO5&quot;]/div[2]/div[1]/div[@class=&quot;WizardPanel_body__21TLo&quot;]/div[1]/div[@class=&quot;AdditionalInfo_section__17Hm0&quot;]/div[2]/div[@class=&quot;FieldSet_container__3odpU&quot;]/div[2]/div[@class=&quot;InputList_editMode__3LmDi InputList_editContainer__1i18K&quot;]/div[1]/div[1]/div[5]/div[@class=&quot;ContactForm_gridrow__1pOGG&quot;]</value>
      <webElementGuid>97096f38-bee6-4a3d-b303-cdd9d02eac20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div[2]/div/div[2]/div[2]/div/div/div[5]/div</value>
      <webElementGuid>ed61ed1c-6d5e-428d-b83d-709adcf6dc05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/following::div[6]</value>
      <webElementGuid>33fcd528-3b17-48f8-bb97-185c95999113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Both'])[1]/following::div[12]</value>
      <webElementGuid>26e2fb76-aef0-4227-b272-6c3e3cbb4dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div</value>
      <webElementGuid>f6f8e7f0-54af-4b3e-92d0-2b53bb66fe25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Email Address*Phone NumberValue entered must be a valid phone number' or . = 'Email Address*Phone NumberValue entered must be a valid phone number')]</value>
      <webElementGuid>74946354-ef42-426a-820e-c09e60385764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
