<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_contact-m9he0twddpj-phoneNumber</name>
   <tag></tag>
   <elementGuidId>5f6ad5d2-c4d8-4aba-8899-c3d9fa04ec1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-m9he0twddpj-phoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact-m9he0twddpj-phoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6b3d6e6-945a-419e-8e75-358883c358d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-m9he0twddpj-phoneNumber</value>
      <webElementGuid>df976787-1707-486f-909d-b65896d23e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9238ae9c-fc27-41a1-82c7-bddbd329762c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>90b4103c-2835-41ab-8462-75bf5c3f9fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2cf122ba-4b7a-4272-b09e-e8cbd648c356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>638f660c-63e6-4117-b40b-e668330a645f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>contact-m9he0twddpj-phoneNumber_1440013438</value>
      <webElementGuid>e3473431-0dd3-4ca0-853f-9d5de8e8f114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>555-555-5555</value>
      <webElementGuid>9365d981-8a95-46c1-a1aa-1bd29c543213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>555-555-5555</value>
      <webElementGuid>0ccf9f05-7e62-4f7f-936b-fcf6a42ae43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-m9he0twddpj-phoneNumber&quot;)</value>
      <webElementGuid>ef7ae3a6-a973-41ef-b83d-e8bdab63be33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact-m9he0twddpj-phoneNumber']</value>
      <webElementGuid>4c86e269-2b91-4b81-a3ff-3b6ce00a54e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div[2]/div/div[2]/div[2]/div/div/div[5]/div/div[2]/div[2]/input</value>
      <webElementGuid>1c5a25de-7cf1-40d5-836c-aa40002ad76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div[2]/input</value>
      <webElementGuid>5ad57abe-ae76-4867-bc45-fdb3af4a9715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact-m9he0twddpj-phoneNumber' and @type = 'text' and @placeholder = '555-555-5555']</value>
      <webElementGuid>47d504c4-c88b-44ea-b417-86c8007e0938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
