<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tes</name>
   <tag></tag>
   <elementGuidId>464d844d-fba0-43d9-b8f3-15af0b7c7620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operationDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='operationDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>342d20ac-e3f4-4729-b791-2e5b4dd80cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operationDescription</value>
      <webElementGuid>20f4c52a-2a71-414f-afa1-4b761365029c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicTextArea__textArea jut__TextAreaField__textArea</value>
      <webElementGuid>becd84f6-5ea4-4da9-baa0-bf11ace246d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d7890e6b-04fc-4f0a-82ca-f1bc094dfafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>operationDescription_1440013438</value>
      <webElementGuid>304685b0-161c-4bf9-beba-4365b337dde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>5101b62f-5fda-4b9c-b368-a9e6994d51ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>106a34a1-6dbd-4f8d-919c-e7cbbd805026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tes</value>
      <webElementGuid>6ab2086c-b540-48e1-8876-7844c974a9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operationDescription&quot;)</value>
      <webElementGuid>f57dab02-b996-40e9-90bd-f248f25af2f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='operationDescription']</value>
      <webElementGuid>dd39edbe-8717-449f-895d-26df35aecfd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[3]/div[2]/textarea</value>
      <webElementGuid>5758e64d-6447-4bf4-bd95-026a87f38cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description of Operation'])[1]/following::textarea[1]</value>
      <webElementGuid>05f68693-455b-4ae4-b6fe-13f6b78402dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Number (For Agency Download)'])[1]/following::textarea[1]</value>
      <webElementGuid>53f8d0ca-204f-4902-9098-9e458b92da73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doing Business As'])[1]/preceding::textarea[1]</value>
      <webElementGuid>153e9fb5-ac3e-4ea3-aac0-a75ab3d250fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Does named Insured Have Any Dba', &quot;'&quot;, 's')])[1]/preceding::textarea[1]</value>
      <webElementGuid>a5aadcdd-3b0d-4b86-b2c4-5e09c436df63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tes']/parent::*</value>
      <webElementGuid>11e8f55e-589d-401b-8c6e-3871602e593e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>dafee739-2edf-45bf-bde6-a4aadc333ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'operationDescription' and @placeholder = 'Description' and (text() = 'Tes' or . = 'Tes')]</value>
      <webElementGuid>2cf8a7a2-771c-4983-b0ac-3ca685783b7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
