<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Test Descripti</name>
   <tag></tag>
   <elementGuidId>443bbdc9-1fcf-4857-af18-339ac1744239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operationDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='operationDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>25c09b1e-7256-40fb-8acb-aa69f7368d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operationDescription</value>
      <webElementGuid>92500cac-7170-4587-bd5d-c50524472d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicTextArea__textArea jut__TextAreaField__textArea</value>
      <webElementGuid>931b616c-ea60-45aa-8970-4ca6806231b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f11b9eb-1bf8-4460-97cb-f1e36081f2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>operationDescription_1440013438</value>
      <webElementGuid>5f6f6470-22ef-46e3-a89c-78ee3aa9254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>7120364c-16ad-4b56-a79e-6f1bd6952fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>3cedf912-608b-4676-8daf-49e00d58c515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Descripti</value>
      <webElementGuid>3270698d-dad2-4e53-b22f-5b6cbfdbd1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operationDescription&quot;)</value>
      <webElementGuid>266cdde8-a760-44fa-bff0-b8635e534b9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='operationDescription']</value>
      <webElementGuid>9401689a-32a4-4fe1-925d-01843c9b6b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[3]/div[2]/textarea</value>
      <webElementGuid>9bd88456-3f4d-4513-a749-8624e048e1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description of Operation'])[1]/following::textarea[1]</value>
      <webElementGuid>cddf5e23-baa4-4fb0-8b54-1f2a1e141232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Number (For Agency Download)'])[1]/following::textarea[1]</value>
      <webElementGuid>aef24d38-812a-4097-ac8d-128ad75ea4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doing Business As'])[1]/preceding::textarea[1]</value>
      <webElementGuid>534a1184-eaf4-4b74-9b74-09d287e57df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Does named Insured Have Any Dba', &quot;'&quot;, 's')])[1]/preceding::textarea[1]</value>
      <webElementGuid>783cceb5-83fa-4cfa-b110-5c8955b75a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Descripti']/parent::*</value>
      <webElementGuid>c8bba163-0bbf-4f6f-a19d-4528cc76a9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>35084a13-3a4f-4cac-8a17-1b881fc705f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'operationDescription' and @placeholder = 'Description' and (text() = 'Test Descripti' or . = 'Test Descripti')]</value>
      <webElementGuid>990f512e-b2e8-4a68-81af-08e80a692adf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
