<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_TEw</name>
   <tag></tag>
   <elementGuidId>33da6103-8380-403e-a0e0-2f3dd8073f04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operationDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='operationDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6950c13e-f7d5-465f-939c-cef4f052475b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operationDescription</value>
      <webElementGuid>0075901d-309c-493e-9ff9-d6798c6b7625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicTextArea__textArea jut__TextAreaField__textArea</value>
      <webElementGuid>6805223e-d51d-478f-8538-fb3c20ce2b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cca912ac-97ac-4878-99e3-f491d4b2c85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>operationDescription_1440013438</value>
      <webElementGuid>091e31b1-3913-4ca0-906e-21d5fad56c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>0aea8a96-bdaa-470b-a985-ef417fc08bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>e4f71e1e-54b2-415d-a744-126d00f582be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEw</value>
      <webElementGuid>1dabc805-6343-411d-a15a-991891b534e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operationDescription&quot;)</value>
      <webElementGuid>a65c2c7f-0a06-42f9-92a8-e5fb8f4bebf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='operationDescription']</value>
      <webElementGuid>b1e9b60e-303f-408c-a191-4c9b1a774828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[3]/div[2]/textarea</value>
      <webElementGuid>75cdc6c0-ea33-417f-b09b-f50716c2eff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description of Operation'])[1]/following::textarea[1]</value>
      <webElementGuid>8a620e02-befd-4529-9ae1-665576ccd607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Number (For Agency Download)'])[1]/following::textarea[1]</value>
      <webElementGuid>f0d21243-3c6b-4228-8234-08b1a7b2debf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doing Business As'])[1]/preceding::textarea[1]</value>
      <webElementGuid>5aab4d4e-4174-4289-86cd-4b8b3ea2f149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Does named Insured Have Any Dba', &quot;'&quot;, 's')])[1]/preceding::textarea[1]</value>
      <webElementGuid>fe47092a-544c-4f34-9c0e-7af23fd97b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TEw']/parent::*</value>
      <webElementGuid>989bcb0a-32c4-44e8-89ec-a2d0f5402165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e79cd4a7-5531-4a1e-b395-a934a377e1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'operationDescription' and @placeholder = 'Description' and (text() = 'TEw' or . = 'TEw')]</value>
      <webElementGuid>6bf50a39-7edc-4f88-aad7-a67248cf3bc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
