<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Test S</name>
   <tag></tag>
   <elementGuidId>75eedb7a-c1d4-4454-947d-5259aca8ed05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operationDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='operationDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0e84fb12-e079-48ca-abfa-073d294ca728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operationDescription</value>
      <webElementGuid>e5eb1e22-9d2b-4766-9add-5c6ffd773719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicTextArea__textArea jut__TextAreaField__textArea</value>
      <webElementGuid>9d1c787a-9758-4b1a-9dd1-a1f2f67969d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>804773cf-65d4-4b45-bef2-1c61b2da47ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>operationDescription_1440013438</value>
      <webElementGuid>aaf1592a-8e2d-40d2-a637-c2fddd274825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>874dc3db-421b-48ce-b9d7-dd193bff68bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>f7d38304-9b12-47f8-aaad-83a2114aa1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test S</value>
      <webElementGuid>b21fbeb2-c5fd-411f-a268-ea8c16bea492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operationDescription&quot;)</value>
      <webElementGuid>ae15bec4-e7b7-419c-87b6-ad7d156402d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='operationDescription']</value>
      <webElementGuid>038f3133-fbcf-489b-9fb6-ea914b1d2418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[3]/div[2]/textarea</value>
      <webElementGuid>353a2dbc-a22e-4605-af54-8b1c895a20d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description of Operation'])[1]/following::textarea[1]</value>
      <webElementGuid>d9345d42-7e43-4221-a6f2-ef32c7461831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Number (For Agency Download)'])[1]/following::textarea[1]</value>
      <webElementGuid>960b2959-e442-49dc-9f28-f48bad3a31cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doing Business As'])[1]/preceding::textarea[1]</value>
      <webElementGuid>52709671-d099-4d05-aa9f-b6de35784531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Does named Insured Have Any Dba', &quot;'&quot;, 's')])[1]/preceding::textarea[1]</value>
      <webElementGuid>37340c85-1b4d-47ee-8d52-e60042bb0368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test S']/parent::*</value>
      <webElementGuid>2c15033c-321a-4410-be6e-f66cb02e1842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f8aff39c-d944-4e93-aee7-5dddb0209189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'operationDescription' and @placeholder = 'Description' and (text() = 'Test S' or . = 'Test S')]</value>
      <webElementGuid>813c3dab-351f-4232-b154-ae7cd61fb601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
