<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Test_1</name>
   <tag></tag>
   <elementGuidId>9e08706c-b6f7-4c08-afe9-e1cb118b0b65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operationDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='operationDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0f91694b-4cb4-4908-9cf5-88b3a0cd44d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operationDescription</value>
      <webElementGuid>ed487ce5-4d82-4a8a-962f-04e30306148f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicTextArea__textArea jut__TextAreaField__textArea</value>
      <webElementGuid>bf779151-4078-48ab-9aff-050a2c7778c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ecca9d6-39e1-43c0-b301-67018061e1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>operationDescription_1440013438</value>
      <webElementGuid>459de2fb-03b8-452d-b306-162b7039381e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>a01b9fd3-c65f-486e-9777-b5dceb85c1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>b72a86c9-56f6-45c2-bf48-c2ce20805ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test </value>
      <webElementGuid>e480178b-dcb1-46d6-b66c-1c3401213cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operationDescription&quot;)</value>
      <webElementGuid>50b22912-5c57-4e28-ad64-e3940468c1d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='operationDescription']</value>
      <webElementGuid>79730d8f-a3e4-4c56-bd20-45567d820bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[3]/div[2]/textarea</value>
      <webElementGuid>758acc07-cb7a-4599-9b13-0dbcc1e9e496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description of Operation'])[1]/following::textarea[1]</value>
      <webElementGuid>fb080b4e-d6a1-41cd-ac9a-1dec9934d8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Number (For Agency Download)'])[1]/following::textarea[1]</value>
      <webElementGuid>e686ff48-fcc4-454c-93b3-c1c2e29e75fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doing Business As'])[1]/preceding::textarea[1]</value>
      <webElementGuid>362523b2-a9cd-4bbf-9c2b-23a31e749c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Does named Insured Have Any Dba', &quot;'&quot;, 's')])[1]/preceding::textarea[1]</value>
      <webElementGuid>17f69161-49ce-4567-b81f-5636c436463f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test']/parent::*</value>
      <webElementGuid>80cd53ac-caa9-4ff2-a5bb-c0c36770b916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>40f5fcd7-74fb-480a-9839-2bb80e7f8e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'operationDescription' and @placeholder = 'Description' and (text() = 'Test ' or . = 'Test ')]</value>
      <webElementGuid>e7ccebc3-5551-4377-ab07-c6faa48d450f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
