<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City</name>
   <tag></tag>
   <elementGuidId>767141e7-d664-4c2d-891e-40f02fca2c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-r4a0nqbgbx-address-tzccygkaju-city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact-r4a0nqbgbx-address-tzccygkaju-city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7afb9f56-3e02-4552-a326-1c25f426abd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-r4a0nqbgbx-address-tzccygkaju-city</value>
      <webElementGuid>ec8c37b8-56da-48e7-8416-07fc77bdc268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a707a1d-cd45-492e-8ce9-809968abe1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>bab046c8-e1d5-4951-bf1f-200542608a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-contact-r4a0nqbgbx-address-tzccygkaju disabled-address-level2</value>
      <webElementGuid>d933e3cd-7e1a-4c08-9990-d50ffe481206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8504b3de-4fa4-417b-8708-6e79fdf63a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>contact-r4a0nqbgbx-address-tzccygkaju-city_1440013438</value>
      <webElementGuid>e45611c1-6b26-4786-9980-27fa51144525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>66538203-a657-467f-b47d-e99d2c5f7f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>3d7a0e2b-e43d-44a9-9209-983c2b9cdf3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-r4a0nqbgbx-address-tzccygkaju-city&quot;)</value>
      <webElementGuid>252e5840-8c35-4b9f-bfde-7b6baad4535c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact-r4a0nqbgbx-address-tzccygkaju-city']</value>
      <webElementGuid>d1deb02d-fa34-4163-a7da-55c0aeb56001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div/div/div/div/div[5]/div/div/div/div[2]/input</value>
      <webElementGuid>071466d2-2eae-4dae-9809-aa41d765a49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/input</value>
      <webElementGuid>c6ab4f0e-1ff4-42a9-b3b6-e16fecd72cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact-r4a0nqbgbx-address-tzccygkaju-city' and @type = 'text' and @placeholder = 'City']</value>
      <webElementGuid>707ca0ee-5c83-4032-b424-2520c340b980</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
