<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Employers Liability</name>
   <tag></tag>
   <elementGuidId>4cf95ad3-83f5-4665-a7a9-c7332e87f3af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-16-option-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-16-option-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>444e63cd-318c-4492-ac07-371cfa82b87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicGenericSelectControl__option jut__GenericSelectControl__option jut__GenericSelectControl__optionFocused css-1n7v3ny-option</value>
      <webElementGuid>9895d89a-0dc8-4416-abc3-5007d14ceade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-16-option-3</value>
      <webElementGuid>fc9adaeb-dc6c-4ba7-ba78-3ac9e5b39d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>11a874b8-02a7-41e3-9f4c-a8a315e321bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employer's Liability</value>
      <webElementGuid>24cea4a8-803c-4ce1-83f1-f69dff7b5e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-16-option-3&quot;)</value>
      <webElementGuid>118893e9-a6b4-49d7-901b-6a394d241103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-16-option-3']</value>
      <webElementGuid>590dc057-e6cb-4bd6-bb50-7580967bd7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprehensive Personal Liability'])[2]/following::div[1]</value>
      <webElementGuid>9ab35e21-db66-4514-93a5-9c5a72e3037a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Liability'])[1]/following::div[2]</value>
      <webElementGuid>98f69cb6-9076-453c-866b-436d3b6b6c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recreational Vehicles'])[1]/preceding::div[1]</value>
      <webElementGuid>0bd1dbe1-0e72-4b4e-8a45-1f4b315a580e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watercraft'])[1]/preceding::div[2]</value>
      <webElementGuid>1352ab67-a24b-4c04-a7b7-eb0ccf78bb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[4]</value>
      <webElementGuid>d641335f-01fe-4113-8ed5-09ffbc9f1c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-16-option-3' and (text() = concat(&quot;Employer&quot; , &quot;'&quot; , &quot;s Liability&quot;) or . = concat(&quot;Employer&quot; , &quot;'&quot; , &quot;s Liability&quot;))]</value>
      <webElementGuid>276070f1-588e-4b8e-ba34-8dfb614fa6b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
