<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Other Policy Type_otherTypeOfPolicy</name>
   <tag></tag>
   <elementGuidId>576cf012-e46f-49e6-ad8b-cecfcdd420f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otherTypeOfPolicy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otherTypeOfPolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b81bcbba-ab67-45e3-9c9f-743fab0ac766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherTypeOfPolicy</value>
      <webElementGuid>1c09f43d-c8dd-4738-bf43-c48ace0884b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>720e730f-1142-4853-a973-0abb2eab5c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input PolicyDetailsForm_control2__2nDnB</value>
      <webElementGuid>0feecf08-0af7-4818-b28f-9517576d3b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>152cfc14-f622-4965-9c5b-d5d30ee2ca30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a8027bb-fcf6-4db6-932f-01650932cbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>otherTypeOfPolicy_1440013438</value>
      <webElementGuid>b49acce5-6361-42f6-9651-873c7ed36737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Other Policy Type</value>
      <webElementGuid>555ada57-41a9-449f-8584-2c0ae7ac0672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Other Policy Type</value>
      <webElementGuid>2127ed99-5d55-414e-ad8f-fc583b0ceb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherTypeOfPolicy&quot;)</value>
      <webElementGuid>90ddd301-1136-47f7-b88f-e296c7d763e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherTypeOfPolicy']</value>
      <webElementGuid>d141cf6e-35dc-4e9a-88d3-a52a3264ec2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>7150d451-ad2b-4e49-97a3-221b315f4a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>6c94bb22-1880-4185-9d06-47875ac097e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otherTypeOfPolicy' and @type = 'text' and @placeholder = 'Other Policy Type']</value>
      <webElementGuid>0fef8042-e94b-489b-9ec9-0e26e5ef05d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
