<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Name of Insured, , s Employer)_cfa305</name>
   <tag></tag>
   <elementGuidId>0bebdcf1-2cbc-41dd-886a-780fe3661cb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insuredEmployer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='insuredEmployer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a84561b-c60c-4490-90c2-1dd10c635269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insuredEmployer</value>
      <webElementGuid>c92e2898-67cf-413d-9ba2-3c3b0e39fb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a85eda0b-1fc9-48de-8a2d-ad7408625da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>da69f4a4-6c8b-4e3c-abfc-1034b2206784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4200b3f0-deab-4bf3-b959-2be8209e8100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6810793a-739f-44d1-bf4f-d5c2141d0aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>insuredEmployer_1440013438</value>
      <webElementGuid>08fc869c-565d-43e7-9da7-9aa37b1b25b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Employer Name</value>
      <webElementGuid>80a584c5-ac46-4370-87f1-c44ea1c3fb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Employer Name</value>
      <webElementGuid>bf3dd002-8289-44fe-900f-12f59f5a4671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insuredEmployer&quot;)</value>
      <webElementGuid>b003e294-9034-4959-b284-56b443355f13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='insuredEmployer']</value>
      <webElementGuid>915e5aa4-9e15-40ba-8838-396a541ca048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[5]/div/div[2]/div[2]/input</value>
      <webElementGuid>2574f058-ff44-4cb6-aae7-70b7c7bc96c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>5e558d60-feea-42cc-bea9-7dcfb37e4b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'insuredEmployer' and @type = 'text' and @placeholder = 'Employer Name']</value>
      <webElementGuid>d9302220-fabf-403b-a5fc-c898206da539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
