<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Occupation (if retired, list prior oc_83c789</name>
   <tag></tag>
   <elementGuidId>7d402c2d-62a4-456b-aa55-89451f9c5248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insuredOccupation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='insuredOccupation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7d62b33-daea-48de-a8f4-c365a08d7e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insuredOccupation</value>
      <webElementGuid>97d29ee3-6fc2-4912-9719-6c047b8fa5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>75e2d581-ade1-4cf6-9d6b-032ffbc40c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>990ac0c2-6c07-4c40-a605-fd881f682574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a7afc508-c89d-4fb8-be04-e679baa8edf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6cb39f8f-8b95-4481-9c4f-41cc94fe8be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>insuredOccupation_1440013438</value>
      <webElementGuid>faf4cab3-f34f-4bae-9a6d-0be51c9bff35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Occupation</value>
      <webElementGuid>acc13f9c-0d7c-4f3a-81cf-a59abb5a5c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Occupation</value>
      <webElementGuid>bebf592b-8dcc-4d34-b6c3-e6a3a0fbc52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insuredOccupation&quot;)</value>
      <webElementGuid>3d8490f9-caed-4f7d-b76c-ebad556434d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='insuredOccupation']</value>
      <webElementGuid>c3fc0c52-2813-466f-9399-a37b89821601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[5]/div/div/div[2]/input</value>
      <webElementGuid>c59fe8dd-e1c3-481b-96ec-889cd950e1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>09d73226-dedd-46a1-a41a-688167d08ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'insuredOccupation' and @type = 'text' and @placeholder = 'Occupation']</value>
      <webElementGuid>df1a111d-b182-4937-9194-e5ce9b670b60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
