<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Accept</name>
   <tag></tag>
   <elementGuidId>95af2674-6aae-4a49-abeb-8cb8f601c8e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#includeUim > div.dynamicRadioButton__radioButton.jut__RadioButton__radioButton > label.jut__RadioButton__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='includeUim']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1dbc0b15-c866-469d-8277-8f60749afc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>includeUim_Accept</value>
      <webElementGuid>d79fb7f0-9aac-4d70-bf90-5a6e843915db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>40229b70-6862-4b75-b2de-cb3e46b6186b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__RadioButton__label</value>
      <webElementGuid>c7e307c3-1a76-4b29-8d09-955ed2f50bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>7f215786-ea58-4664-982e-95b64069f525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;includeUim&quot;)/div[@class=&quot;dynamicRadioButton__radioButton jut__RadioButton__radioButton&quot;]/label[@class=&quot;jut__RadioButton__label&quot;]</value>
      <webElementGuid>5b20abe3-0c14-4a18-98fd-92e8ef63ef9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='includeUim']/div/label</value>
      <webElementGuid>b69d4e60-d059-4279-a84f-56d96bc4c1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include UIM Coverage?'])[1]/following::label[1]</value>
      <webElementGuid>82c1492d-89a7-464f-830c-9cf6cc7e298a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/following::label[2]</value>
      <webElementGuid>bbf6a57a-1361-45ef-b2b4-2fa9e344c0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[2]/preceding::label[1]</value>
      <webElementGuid>434fe9ff-474d-4d18-8e5b-eb9e8b5009f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/label</value>
      <webElementGuid>36d1e4ca-0761-4a7d-9cb3-6f38a7d8ec5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>3e690318-943a-4b8c-9b68-03699c8c74df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
