<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Print</name>
   <tag></tag>
   <elementGuidId>4103302a-d9ba-4aba-9f1e-31c514d44eb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.PrintReceiptModal_buttonContainer__1oBU5 > button.dynamicButton__button.jut__Button__button.jut__Button__primary > span > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0debd4d-6702-40c5-9e9b-0b9ba6c5887d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Print</value>
      <webElementGuid>e0a3f6b9-ec07-44da-a786-2cdbe6252965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;gw-branding-agencyportal&quot;]/body[@class=&quot;themeRoot dynamicRoot ReactModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open jut__ModalNext__overlay&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open dynamicModal__modal jut__ModalNext__modal dynamicModal__modal&quot;]/div[@class=&quot;jut__Grid__grid jut__Grid__vgapNone jut__Grid__hgapMedium&quot;]/div[@class=&quot;jut__ModalFooter__modalFooter&quot;]/div[@class=&quot;jut__Flex__gwFlex jut__Flex__gwGapMedium jut__Flex__gwJustifyContentCenter jut__Flex__gwWrap jut__Flex__gwDirectionRow&quot;]/div[@class=&quot;PrintReceiptModal_buttonContainer__1oBU5&quot;]/button[@class=&quot;dynamicButton__button jut__Button__button jut__Button__primary&quot;]/span[1]/span[1]</value>
      <webElementGuid>05062038-35d7-463a-8eac-30eb34910f13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::span[2]</value>
      <webElementGuid>212c1ad6-dbfc-4a7f-adaa-523d829a7c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agency Code'])[2]/following::span[4]</value>
      <webElementGuid>3e7a7c62-a04c-4b66-b820-dddc18770bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Print']/parent::*</value>
      <webElementGuid>24bd7c2d-e086-466d-b687-5952e2550893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>8b52c804-66cc-4c3f-b9b2-82abbd37d0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Print' or . = 'Print')]</value>
      <webElementGuid>a46018d2-511e-4633-a052-68487e98b792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
