<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Damage_propertyDamage</name>
   <tag></tag>
   <elementGuidId>3c604e6c-f04c-4d92-9393-5c2acb17f20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#propertyDamage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyDamage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48a3055d-13a7-48da-ad82-8eb19718c64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyDamage</value>
      <webElementGuid>943c76bb-50f0-4a65-914c-6f0ebb5b356f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3896c0da-ce02-4c04-85e6-90236781fc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>c61ce234-4f04-40c6-b04c-66e3ebb7bcd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>15862dd1-3100-4bc4-aa63-145f888d5f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>602d1eaa-d6d3-46d6-803a-3e504f2b91c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>propertyDamage_1440013438</value>
      <webElementGuid>0655a986-15a7-4335-82e5-da6b8890fc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>100,000</value>
      <webElementGuid>5a9f5fa8-2e90-4f42-bee7-41b743dbd40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>100,000</value>
      <webElementGuid>d8509e98-313b-4183-a4bc-f6d39a35fe21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyDamage&quot;)</value>
      <webElementGuid>72098e7d-be24-41ff-9c38-64425602cc62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyDamage']</value>
      <webElementGuid>1fe5f70b-8d22-4fca-adb4-344c4837c900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[4]/div[2]/div/div/input</value>
      <webElementGuid>912d77d9-1b1d-4bf7-bb1d-acf549c4abc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>b9b7dd4a-eca1-4794-a397-8eba8f6ed90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'propertyDamage' and @type = 'text' and @placeholder = '100,000']</value>
      <webElementGuid>4f0dcf1a-a164-4e50-8ee8-b27cb1a375ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
