<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Limit Per Person_perPerson</name>
   <tag></tag>
   <elementGuidId>65594ec4-03e2-4029-bc40-b22cf4592984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#perPerson</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='perPerson']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f893592-a303-4614-817f-56c73bf9baad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>perPerson</value>
      <webElementGuid>f2d7e2cd-eb67-47cd-9a94-204f6f91ae42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a81ee83-1bd8-4c28-9324-dbd7d87714e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>ef80a61a-0341-4be5-be59-1c3fd9196bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b809779b-d348-4d84-b880-ca0e55d71d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6f95135-1fad-4d60-942d-ab4b13116b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>perPerson_1440013438</value>
      <webElementGuid>c4d943f1-3dcb-4549-a7af-fe17bc339946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>500,000</value>
      <webElementGuid>e1b44b9a-0292-421c-84f6-5ab33191a2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>500,000</value>
      <webElementGuid>1440a0e3-b9e9-442f-8671-ca6a85285036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;perPerson&quot;)</value>
      <webElementGuid>4dcb5c3f-e4fb-4251-94c6-243b6468b01d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='perPerson']</value>
      <webElementGuid>dd50a704-cd42-4eda-be28-21e1fbd91439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>bae0aae9-3d08-440e-881a-91438526bc58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>910b0829-60c4-4ce0-92d0-0c434f569328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'perPerson' and @type = 'text' and @placeholder = '500,000']</value>
      <webElementGuid>3a80a12b-2579-4ee4-9dad-223213441a72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
