<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Combined Single Limit_combinedSingleLimit</name>
   <tag></tag>
   <elementGuidId>13d23800-20c4-4867-bfe5-6a518da1f9fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combinedSingleLimit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combinedSingleLimit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e23ed206-61b6-418f-ab8e-eaab10d0c5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combinedSingleLimit</value>
      <webElementGuid>d30ffdac-3956-44d7-8b58-fc8411b24736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e27c42ef-0217-44b2-96f6-666f10ef22c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>32f6dfe6-1829-4b81-99f7-92a9ee5ac4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0e69ff13-0fd5-4323-9a4d-939879b48e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f49c9b7f-cdab-48ee-887f-f53d558ddb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>combinedSingleLimit_1440013438</value>
      <webElementGuid>e1a8238f-833c-44a9-853d-1bc37cbe6880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>500,000</value>
      <webElementGuid>1c6d2e8e-a5bc-452c-8c50-2bde9ca76532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>500,000</value>
      <webElementGuid>5a87fe37-c761-4812-a7bc-515d2b34e967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combinedSingleLimit&quot;)</value>
      <webElementGuid>077eb37a-c2cb-4495-920c-f158a64c8a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combinedSingleLimit']</value>
      <webElementGuid>f78e7b1a-1356-4ed5-96c1-4a49fa701c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[5]/div[2]/div/div/input</value>
      <webElementGuid>8fecb325-3de5-42d3-8ee1-f3de3d7c36e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>5647dd24-6cf7-4746-acb7-f2fe40e844a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'combinedSingleLimit' and @type = 'text' and @placeholder = '500,000']</value>
      <webElementGuid>27d3574f-9313-4ef2-a90b-921c1118a29c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
