<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exp Date_ccExpDate</name>
   <tag></tag>
   <elementGuidId>ccff59fa-3215-4ef3-8b0d-0665652f29f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ccExpDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ccExpDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>696e31b2-75f3-439f-9ea4-b7e377fdabfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ccExpDate</value>
      <webElementGuid>01fe6c86-506c-47a7-9100-daaf7cc0d55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a56efaa6-8799-4f46-afac-d642337ea397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicInputMask__inputMask jut__InputMaskField__inputMask jut__InputMaskField__empty</value>
      <webElementGuid>e3141c55-e78c-456f-a0a6-6935f1bd04d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a0cfbebf-321e-4189-9d7b-2cb2ed954a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>599aad3d-6d0b-44e6-b0c1-49d29c83f612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ccExpDate_1440013438</value>
      <webElementGuid>5c8bc7cb-58bd-45cc-8148-77b587bbcaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>MM/YY</value>
      <webElementGuid>053a98f0-fafb-48c7-be06-30f9132aef3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/YY</value>
      <webElementGuid>bac3e989-34de-4dff-8091-d5a1db64fc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>MM/YY</value>
      <webElementGuid>d5f8963f-e470-417b-8111-05fa28bf9322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccExpDate&quot;)</value>
      <webElementGuid>ace6927a-ddb5-452f-9859-16aa2f16c9fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ccExpDate']</value>
      <webElementGuid>61b8dfb5-5503-474c-acdf-bac5ecbe14c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='creditCardGrid']/div[3]/div/div[2]/input</value>
      <webElementGuid>677818c4-2237-420d-a5a9-3c4147deb7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>7a2af028-2210-46c9-8e67-be51afc9dffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ccExpDate' and @type = 'text' and @placeholder = 'MM/YY']</value>
      <webElementGuid>28e8c824-c332-4b1e-9d4e-0bcf4caa4006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
