<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agent contact name_agentContactName</name>
   <tag></tag>
   <elementGuidId>8af23944-076b-4d2c-a455-8238c0438593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agentContactName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='agentContactName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74900fee-4673-4929-9647-2349ca9297f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agentContactName</value>
      <webElementGuid>68527f48-eb46-4c4b-ba05-ca99453a7610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a55c283-609d-4fdb-8d50-986d0e040628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>7c178b39-bf28-4b38-a6b3-37291e279c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8df6a958-b6d2-421e-b284-b60c2d4eb566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fbd7fe62-e990-4827-941d-6eee523aa771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>agentContactName_1440013438</value>
      <webElementGuid>7ea9c1fc-97b1-4377-a96c-f775d89f0e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agentContactName&quot;)</value>
      <webElementGuid>6ec90212-a924-42f2-9c64-6e3ebe08b32f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agentContactName']</value>
      <webElementGuid>0f485d30-97a8-441f-b404-58bcd4b3f39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='agentContactInformation']/div/div/div[2]/input</value>
      <webElementGuid>a55d8051-3fe8-4838-a7f3-9607f34a91c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/input</value>
      <webElementGuid>e342a54c-7c25-4c09-afd0-e37c55047b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'agentContactName' and @type = 'text']</value>
      <webElementGuid>fabff3c0-73e1-4fec-b4f2-565136721703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
