<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_ccZipCode</name>
   <tag></tag>
   <elementGuidId>5d68429d-1d19-42f2-a779-31660df63fb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ccZipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ccZipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3068be3-94d6-47fe-a9b5-c1f25b30b6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ccZipCode</value>
      <webElementGuid>0b538b0d-fcee-4d58-90dc-401b594eeb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2abd1d5c-811d-4ead-b473-c3e5a1138d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicInputMask__inputMask jut__InputMaskField__inputMask jut__InputMaskField__empty</value>
      <webElementGuid>773de4c1-d472-482b-86d5-a1025ee08778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d8af5f6e-7e9d-4c4e-8545-cdc3f6a4d05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aa238987-5e2a-4f5c-9c9e-d1056ab9a843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ccZipCode_1440013438</value>
      <webElementGuid>fae839ba-0a35-412b-925a-2c17ae1a7aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>599cff35-d11d-4a69-b24b-9e754242a7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>4ed7f1ca-6a06-49a1-a03c-fbf0eaf22803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>e623affd-96ab-41e2-9db4-86dc2d500349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccZipCode&quot;)</value>
      <webElementGuid>9dbc390a-473b-433a-9b2e-2d076a6af272</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ccZipCode']</value>
      <webElementGuid>35d94ac9-ed67-4b07-a482-a2e6ffbd70f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='creditCardGrid']/div[5]/div/div[2]/input</value>
      <webElementGuid>7c20700c-ccdd-453e-98f6-d828d463bc53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>3d52dd4a-98fd-48ea-b196-8fc5dd825ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ccZipCode' and @type = 'text' and @placeholder = '12345']</value>
      <webElementGuid>0b6f591c-76f0-407d-9488-f7b9fa8cd81c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
