<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Monthly</name>
   <tag></tag>
   <elementGuidId>03077b8f-dbb1-468c-8109-9cbbdae5d233</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='billingAndPaymentsCard']/div/div[2]/table/tbody/tr[5]/td/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>99906a09-8fff-45d3-90dd-606565bc761a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>paymentPlan_4_db_monthly</value>
      <webElementGuid>31c390e7-6d71-462c-b3c3-fcd915132bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__RadioButton__label</value>
      <webElementGuid>6914a3fe-1c9c-49a2-95e9-6492a014f012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monthly</value>
      <webElementGuid>4d5dc925-1fa3-4d46-81b0-05f225189846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingAndPaymentsCard&quot;)/div[1]/div[@class=&quot;dynamicTable__table jut__Table__table jut__Table__hoverable hmic__Table__default hmic__Table__alternatingRowColorsFlipped PaymentStep_dataTable__2o3PO&quot;]/table[@class=&quot;jut__Table__tableElement&quot;]/tbody[1]/tr[@class=&quot;jut__Table__row&quot;]/td[@class=&quot;dynamicTable__tableCell jut__Table__tableCell text-left&quot;]/div[@class=&quot;dynamicRadioButton__radioButton jut__RadioButton__radioButton jut__Table__radio&quot;]/label[@class=&quot;jut__RadioButton__label&quot;]</value>
      <webElementGuid>14123d26-5473-4b4b-8027-57bcf33c7980</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billingAndPaymentsCard']/div/div[2]/table/tbody/tr[5]/td/div/label</value>
      <webElementGuid>6da7a6f1-260f-4bac-b18f-74826324f223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$180.00'])[6]/following::label[1]</value>
      <webElementGuid>4c1bbb9c-931f-47bb-b763-6f4549c20f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$45.00'])[2]/following::label[1]</value>
      <webElementGuid>cb995d9a-37c4-4ba5-b082-dc5e4b2afdba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$30.00'])[3]/preceding::label[1]</value>
      <webElementGuid>6b0f344e-af5d-42b5-9d0e-b67220e008cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div/label</value>
      <webElementGuid>a03aece2-e9b4-4526-8631-2538cd3f0e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Monthly' or . = 'Monthly')]</value>
      <webElementGuid>367a59ab-ee17-482c-ba48-2e3a01ae2c30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
