<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save</name>
   <tag></tag>
   <elementGuidId>c81ea966-4dea-4e81-b09a-607ac44fbee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jut__Flex__gwFlex.jut__Flex__gwGapMedium.jut__Flex__gwAlignItemsCenter.jut__Flex__gwJustifyContentCenter.jut__Flex__gwWrap.jut__Flex__gwDirectionRow > button.dynamicButton__button.jut__Button__button.jut__Button__primary.colorAccent > span > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='saveCancelPI']/div[2]/button[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>60822003-990e-45de-8a34-3956bc7b9630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>691ef9eb-709c-4d09-a2ee-dfc63fed55f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveCancelPI&quot;)/div[@class=&quot;jut__Flex__gwFlex jut__Flex__gwGapMedium jut__Flex__gwAlignItemsCenter jut__Flex__gwJustifyContentCenter jut__Flex__gwWrap jut__Flex__gwDirectionRow&quot;]/button[@class=&quot;dynamicButton__button jut__Button__button jut__Button__primary colorAccent&quot;]/span[1]/span[1]</value>
      <webElementGuid>9aa9cfda-34d7-42b0-90bc-a73ba3bd3cea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='saveCancelPI']/div[2]/button[2]/span/span</value>
      <webElementGuid>d157e501-1458-47d2-bb5c-e3d092d815d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[2]</value>
      <webElementGuid>155749d0-24c7-468a-9526-8d4a4a193c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code'])[1]/following::span[4]</value>
      <webElementGuid>9dde5b43-3b69-4804-8018-f5fd23d058f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change payment plan at renewal?'])[1]/preceding::span[2]</value>
      <webElementGuid>ee32dc06-e62f-4261-af77-a2503427fc22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent Contact Information'])[1]/preceding::span[3]</value>
      <webElementGuid>25b3a10a-5548-4ba4-b39b-c7ab2c95fcff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>d4936658-bbd7-45b9-9cfc-34289e44270d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>971c151e-b0ac-4662-829a-cc473decc858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>101a3220-8999-4285-bdc7-6df0f5988d2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
