<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Submit Payment</name>
   <tag></tag>
   <elementGuidId>0f341fa5-74fd-4148-b266-29af93021c37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#okButton > span > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='okButton']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39ebbfdb-1511-4f97-9a72-b56712bc8001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Payment</value>
      <webElementGuid>5f230361-9858-4104-843c-cca2084537ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;okButton&quot;)/span[1]/span[1]</value>
      <webElementGuid>ec8d2509-f641-4e2c-abc4-95de83bd2426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='okButton']/span/span</value>
      <webElementGuid>7bfcdf17-d7cc-42d8-8f17-d19df5eeb977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::span[2]</value>
      <webElementGuid>8749a90e-ff1d-4cbf-9839-04e15aa9d0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please confirm'])[1]/following::span[4]</value>
      <webElementGuid>995577ef-6864-4934-9568-1932bc9886a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit Payment']/parent::*</value>
      <webElementGuid>37af3ec2-d8da-43b7-94db-16f0d3fa5241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[3]/div/button[2]/span/span</value>
      <webElementGuid>283f85c2-1693-4e8d-b926-59e20dd2edf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Submit Payment' or . = 'Submit Payment')]</value>
      <webElementGuid>c75a9f06-ceed-40a4-9b78-59da18524569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
