<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Combined Single Limit_combinedSingleLimit</name>
   <tag></tag>
   <elementGuidId>c34fdcdc-92a1-4054-a2c7-e0665674d62f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combinedSingleLimit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combinedSingleLimit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87f1ca5b-705c-4aa4-8945-c00a0ca31358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combinedSingleLimit</value>
      <webElementGuid>cb53ab9a-0a6d-45f5-9754-935e0d89ef49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a968123f-f47f-4cdc-b7dd-08df0783d3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>96a70224-3899-4115-8c36-81d4de557652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1b95310d-5648-4b18-850a-0e9580b97725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>698ca7e7-e789-4387-998b-a54aafca2f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>combinedSingleLimit_1440013438</value>
      <webElementGuid>cc10b9a1-8f00-402d-a096-5911830aca85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>500,000</value>
      <webElementGuid>0105124e-6960-4376-81c7-4bf8960fa66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>500,000</value>
      <webElementGuid>92dcf42c-b52e-4be8-8a2e-04f2b4b6b171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combinedSingleLimit&quot;)</value>
      <webElementGuid>9c305cac-6ae8-4220-897b-f545c25b70d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combinedSingleLimit']</value>
      <webElementGuid>633859a9-d2d8-4d0e-9683-9cb0f068b2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[5]/div[2]/div/div/input</value>
      <webElementGuid>025bccd2-9500-4f13-8f64-152d5f66d6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>70c77245-74d3-4dd9-951b-42f559b54ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'combinedSingleLimit' and @type = 'text' and @placeholder = '500,000']</value>
      <webElementGuid>a3485a94-5336-4984-bc19-6e0cb56705e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
