<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Other Policy Type_otherTypeOfPolicy</name>
   <tag></tag>
   <elementGuidId>2ab2a78a-b941-4dc5-9532-6895a2b66ebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otherTypeOfPolicy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherTypeOfPolicy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c64d326-10b3-40b5-a905-ac9b817115a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherTypeOfPolicy</value>
      <webElementGuid>8a6d484d-4edf-4c25-8b3c-8f4b9cd4b90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1cc93855-5392-4195-8063-de863da6be16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input PolicyDetailsForm_control2__2nDnB</value>
      <webElementGuid>bb86eead-053c-444f-91d0-2d29b6e5e4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4fa227c2-3b6e-4773-bfab-9389b327e81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d59af60f-e6e2-47df-a17c-3a5671ed02a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>otherTypeOfPolicy_1440013438</value>
      <webElementGuid>693fd974-91c6-439f-aa83-0cf67c13ab73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Other Policy Type</value>
      <webElementGuid>90efc312-473a-4374-b503-ec0672946aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Other Policy Type</value>
      <webElementGuid>d8ce1a5f-e58b-47e4-a98c-70d0f645380a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherTypeOfPolicy&quot;)</value>
      <webElementGuid>4fa0edbd-2cfe-4ec3-9dcb-f88abb0fe75c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otherTypeOfPolicy']</value>
      <webElementGuid>ad3e2f7a-be7a-408a-b040-ad6475fe259b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>3f8942a6-3df7-45c9-8fb0-8b38c02c9ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>7fc31d32-bdf4-4d7b-863a-959787c457f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otherTypeOfPolicy' and @type = 'text' and @placeholder = 'Other Policy Type']</value>
      <webElementGuid>7233d43a-6bc5-4f1b-be52-fbc7631d5da7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
