<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_length (in feet)_length</name>
   <tag></tag>
   <elementGuidId>979cb077-67cc-4b4f-9cbc-542a8c8a9d90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#length</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='length']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78ec3762-7e6e-42b4-979a-ac36dc1ace69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>length</value>
      <webElementGuid>975b7984-4a6f-4230-b251-97bffe45a319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7526bc03-9eac-4999-847b-25e440b51ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>a6494c38-e530-45d3-9603-d68b61d277e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>085a39e7-bd94-4195-ac45-8dc96fe37f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b09a5ab1-ce36-4762-af56-910525654711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>length_1440013438</value>
      <webElementGuid>098034c6-4514-486c-b377-373367d7cd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>77ca1940-2387-4ebe-a775-548a0ebb1738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d7ea7ae7-b53d-4d08-8d24-228bfe8a73f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;length&quot;)</value>
      <webElementGuid>f8b3dcdd-480f-4d45-bd2f-702b6349f25f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='length']</value>
      <webElementGuid>4f0535ca-8088-49e9-86c7-e4d6ff2ade84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[4]/div/div/div/div/div[2]/div/div[2]/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>745780ba-9a26-471b-9314-5d468f4080a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>03b52418-0c4a-4d9d-b627-455eb5307d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'length' and @type = 'text' and @placeholder = '20']</value>
      <webElementGuid>44ec6ed0-1828-43ff-b09c-c01f0618bd92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
