<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Engine Size_engineSize</name>
   <tag></tag>
   <elementGuidId>bd1e558c-d1a8-4d93-ab57-544338747072</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#engineSize</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='engineSize']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30d635cf-6b5b-4b44-b020-1c491a1ba0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>engineSize</value>
      <webElementGuid>a072b2d2-c619-4291-9196-5e1bed160d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>082b65c9-f8ba-442c-95a6-f433ee7c5abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>750cd6b8-c9cd-4ddb-90c6-82cf952e98df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3cc63e6e-9b5c-4c3a-ad90-9012bc7885d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bbe9bd5e-cb1e-4ddb-aa60-224770c0dcc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>engineSize_1440013438</value>
      <webElementGuid>b7dc55b7-2f2c-4107-94fc-949eb835a4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>930196b1-17eb-4827-9684-07a2c55edad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>bd793693-e322-4452-bea8-fd1cd4d4585a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;engineSize&quot;)</value>
      <webElementGuid>cd8ef6fc-3a18-4a6e-a224-4b91d5b12584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='engineSize']</value>
      <webElementGuid>10747b78-dd64-4fc8-a3d0-55789a9e1f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[3]/div/div/div/div/div[2]/div/div[2]/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>fadb01c0-6cc0-4ca7-8bf5-6530a9d4f99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>4f7eb1d3-8ea5-4f38-b492-d68235e3f275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'engineSize' and @type = 'text' and @placeholder = '200']</value>
      <webElementGuid>d41c9831-44e6-4dd9-ad2f-c8a42ef98ecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
