<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Model_model (1)</name>
   <tag></tag>
   <elementGuidId>c3209e41-771e-4f47-b5f9-a7ad8ba01795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#model</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='model']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7769ad1-bf6c-410a-bd69-991fadf93cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>model</value>
      <webElementGuid>8fafa8ce-26fc-4f54-b576-50fa206fe591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a122668-5a26-4468-80ac-dec2459f167e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>8fcdad14-dc81-4949-8402-758ab0db6ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>dab512fe-1eb2-43b5-ba7b-2da0491af303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29e6bd82-90d5-4769-a1c2-3c4dab2e6308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>model_1440013438</value>
      <webElementGuid>88f94377-4e88-48b6-9857-113d5aa7d3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Model</value>
      <webElementGuid>4ff6febb-11e0-4e35-9f4b-a8920ea2a501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Model</value>
      <webElementGuid>47c9fac7-2a0d-4bb4-b66b-1b82bd60553f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model&quot;)</value>
      <webElementGuid>b7290f3a-883b-4077-953f-c9d99bc71d59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='model']</value>
      <webElementGuid>d2be8ad9-4139-4ed0-97e5-34d5af7a71b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[3]/div/div/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>d918a046-3752-47f3-8127-1cf6a4672c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>2a2eea47-4e56-4636-94d8-a2e863b53c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'model' and @type = 'text' and @placeholder = 'Model']</value>
      <webElementGuid>841c8c26-9382-4fc4-a96c-737652d475a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
