<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FEIN_contact-3ox9ujv960h-feinId</name>
   <tag></tag>
   <elementGuidId>96950a9e-3c6b-4a24-b338-4eb5fe464692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-3ox9ujv960h-feinId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact-3ox9ujv960h-feinId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18c9e2b3-cb91-43e7-a5c5-82b638d0ce1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-3ox9ujv960h-feinId</value>
      <webElementGuid>b283f5d2-ba65-4a0d-ba2d-d7e70e3cb26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0549146-edd0-467a-8443-f81b5860c752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicInputMask__inputMask jut__InputMaskField__inputMask jut__InputMaskField__empty invalid</value>
      <webElementGuid>e7e370a7-32b6-487f-b7c9-daf40afae743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f20d3c5a-5841-4719-8ea8-c2234ead35ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26acd6fb-be89-4d29-986f-54ae22e67929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>contact-3ox9ujv960h-feinId_1440013438</value>
      <webElementGuid>2c02ee20-f6fa-46e3-9e78-fede35ba838f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>d86fe278-76fc-4100-8bb9-a734f91a5edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>425b2c45-8888-4016-be5f-48cf6728f7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>0038718f-1464-451e-bd9d-9c29b525f387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>__-_______</value>
      <webElementGuid>76ebef4e-1729-4321-be9d-ee5e4be92cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-3ox9ujv960h-feinId&quot;)</value>
      <webElementGuid>14dff5f8-2dfe-4ca6-9a9b-407e69ed92f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact-3ox9ujv960h-feinId']</value>
      <webElementGuid>bff82d49-9c4d-4548-b9b0-8c99a27d5331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[5]/div/div/div[2]/div/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>ce9b5575-218f-475d-bc39-b546c4553fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/input</value>
      <webElementGuid>8ef20fd4-2a40-4821-8021-bde6b23abfb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact-3ox9ujv960h-feinId' and @type = 'text' and @placeholder = '#########']</value>
      <webElementGuid>fcd2014f-250d-46ef-94d2-f595e18b4038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
