<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FEIN_contact-3ox9ujv960h-feinId</name>
   <tag></tag>
   <elementGuidId>96950a9e-3c6b-4a24-b338-4eb5fe464692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='FEIN']/../../..//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contact-3ox9ujv960h-feinId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44229f3b-9809-49e9-b4ca-c9a8365eb67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-3ox9ujv960h-feinId</value>
      <webElementGuid>1d8fc544-bfe3-4ebd-a264-939e13512322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d30b2915-89a9-4c0c-805c-3988c2727ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicInputMask__inputMask jut__InputMaskField__inputMask jut__InputMaskField__empty invalid</value>
      <webElementGuid>2702d682-9e57-40ca-b3a0-4c688357bda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>064ad5a2-9a80-42d5-9d01-fcd093ba43df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c0e84eb-f431-4415-8ebd-9e5032f36461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>contact-3ox9ujv960h-feinId_1440013438</value>
      <webElementGuid>a425f2b1-5557-44e3-935b-bf67eed457ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>657812d0-5929-408f-aef3-4e3547d7e590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>7eb099d8-a227-4644-893d-1fd16e108465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>ceb468f3-cac5-4812-8be8-4e0c93d7d435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>__-_______</value>
      <webElementGuid>4dfc53d7-c49f-4c77-8fc6-ab7f502ea616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-3ox9ujv960h-feinId&quot;)</value>
      <webElementGuid>6fcde50f-4384-4501-9e83-1eabae7b688d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact-3ox9ujv960h-feinId']</value>
      <webElementGuid>b5995767-ee5a-45bb-93d3-ba3c113f77b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[5]/div/div/div[2]/div/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>6211d856-68c7-40be-8c7c-1f2bc15b9631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/input</value>
      <webElementGuid>54660345-b9ad-40f8-89ac-b32398fa669f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact-3ox9ujv960h-feinId' and @type = 'text' and @placeholder = '#########']</value>
      <webElementGuid>af590b13-5261-421d-924e-3897738e7d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
