<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Occupation (if retired, list prior oc_83c789</name>
   <tag></tag>
   <elementGuidId>5d39c8a8-fe5c-4a5d-a826-cdb8155a0fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insuredOccupation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='insuredOccupation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba3d1373-b12c-40ff-979f-269c27dd78fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insuredOccupation</value>
      <webElementGuid>222e541a-fdbd-47e1-a246-65925409bb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ce7577a-a249-4a50-9ef1-8258df6604a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>571671d8-f49b-4148-a741-5d32eab8a0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c50ce684-0615-4e0e-8d4d-b9bd56897eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2396ff46-0229-4368-8530-80a37cb27bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>insuredOccupation_1440013438</value>
      <webElementGuid>b9cc6545-43a6-49b0-ac4c-a761854fe2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Occupation</value>
      <webElementGuid>0221b1e5-a06b-49c9-a805-8873b9625ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Occupation</value>
      <webElementGuid>d3e971d0-ce01-4aab-91c0-07a5c2aac845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insuredOccupation&quot;)</value>
      <webElementGuid>88c1ac35-66e4-4a11-8b0d-27e2c1b2e67b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='insuredOccupation']</value>
      <webElementGuid>58f6a924-986a-4831-8ed5-151f314db6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[5]/div/div/div[2]/input</value>
      <webElementGuid>30e00cd2-eb37-4c12-a1e2-7d72a73fcea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a2c4e225-7df6-4c95-b1c7-1f4092840d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'insuredOccupation' and @type = 'text' and @placeholder = 'Occupation']</value>
      <webElementGuid>e9ce86e6-e835-4b95-98c7-f1a61057ab09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
