<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier_carrier</name>
   <tag></tag>
   <elementGuidId>87bd4e94-681c-4bd0-98d4-3f0fef4d9348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#carrier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='carrier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4eb5f01b-48df-4b09-9c9d-20de395fbd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>carrier</value>
      <webElementGuid>2377dc3d-c0aa-4deb-a9e8-6ee993e8d2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72ea064e-2cb3-483b-ae2a-2cac292eda34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>5e44e867-16fd-4140-ab71-6c8acc611838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>43fa8ade-2680-4729-944f-fc7fd78a69f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8110d7e4-03c0-48ce-915a-3d249f116287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>carrier_1440013438</value>
      <webElementGuid>09c03c89-6a31-49ac-87b1-cde80709ed29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Carrier Name</value>
      <webElementGuid>bd2a046a-1cb0-4e88-863d-8e9ce656d70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Carrier Name</value>
      <webElementGuid>4ded44b0-69b4-43cf-8a21-bfe9db33e89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carrier&quot;)</value>
      <webElementGuid>4300d9b8-b213-414d-a88d-c2501d5ed594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='carrier']</value>
      <webElementGuid>3f0aad94-8e77-4586-b36f-26f084746cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[5]/div/div/div/div/div/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>4d598661-21b8-4fc1-bdd0-a00fc641c301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>03320fd0-bb45-4f45-bd1f-5a20357772fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'carrier' and @type = 'text' and @placeholder = 'Carrier Name']</value>
      <webElementGuid>77d1bb3e-b2ea-4f78-90d5-b867c71f0d9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
