<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2024</name>
   <tag></tag>
   <elementGuidId>d6fe9842-a8e0-43ac-ab8c-6086df216b9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-30-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-30-option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab286ba8-a78c-4042-8c4b-aa27dcd1fd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicGenericSelectControl__option jut__GenericSelectControl__option jut__GenericSelectControl__optionFocused css-1n7v3ny-option</value>
      <webElementGuid>405d4f56-adc2-430e-81a1-fe2c3d93b4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-30-option-1</value>
      <webElementGuid>6960ce16-1fd0-4f74-9115-d14601e15dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d32d6292-085e-4a0c-a5f9-3372d777fb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>0f9da415-b4f8-4951-94d6-b28a1352e604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-30-option-1&quot;)</value>
      <webElementGuid>f2162043-c66c-4447-8b6f-87286ea1bc18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-30-option-1']</value>
      <webElementGuid>d6886834-233e-4c34-97b8-7f2438c5feaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[4]/following::div[1]</value>
      <webElementGuid>6f7f6e93-9f57-4334-8e0f-f554c484bd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'react-select-30-option-1', '&quot;', ')')])[1]/following::div[9]</value>
      <webElementGuid>de72b14f-e5b2-4a51-b66d-ccd77f0ab648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-1981'])[1]/preceding::div[44]</value>
      <webElementGuid>2405ffc4-af6e-49c5-9bbd-f8eae254e93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2024']/parent::*</value>
      <webElementGuid>3f2bfe62-12ca-468e-b240-b65dd9671594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]</value>
      <webElementGuid>51ff7f79-1e18-423f-9280-946528072c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-30-option-1' and (text() = '2024' or . = '2024')]</value>
      <webElementGuid>30b24cc0-926d-44c7-bb46-50787856a386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
