<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Occupancy  Interest_occupancyAndInterest</name>
   <tag></tag>
   <elementGuidId>56d6cb19-2a5c-4948-896c-4d87f5aed994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#occupancyAndInterest</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='occupancyAndInterest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32af633c-310b-4d2c-8d13-c407db7d2917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>occupancyAndInterest</value>
      <webElementGuid>03010926-210a-45cd-9b93-0f3a5191af92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e38ac47b-40f2-49a5-ad45-20bf787afc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>3572251c-069e-4e35-9405-e72d7ed3bf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6ee704ec-da42-4a2b-b34b-87c17edf4412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>151d53c5-f6d8-4d55-9d70-0d31cfa10e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>occupancyAndInterest_1440013438</value>
      <webElementGuid>dba5c382-ef50-459d-9cde-95612f8090d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Owner, lessee, etc..</value>
      <webElementGuid>f2733983-9f5b-42b0-8c04-5922b469c985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Owner, lessee, etc..</value>
      <webElementGuid>452fa845-4ef0-484c-87c5-ec8a0e36f297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occupancyAndInterest&quot;)</value>
      <webElementGuid>e1dd2a91-2d4f-42e1-8a1a-55e4004a105c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='occupancyAndInterest']</value>
      <webElementGuid>3705059a-775f-4b48-b73a-c8b7f6e0100a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>b163e1b1-f4d8-4dac-ae73-b080a7760592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>d8bb0b37-3929-466d-958a-04ad1886b601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'occupancyAndInterest' and @type = 'text' and @placeholder = 'Owner, lessee, etc..']</value>
      <webElementGuid>4ad34843-f447-4067-9436-75f5b1f20d04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
