<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Yes</name>
   <tag></tag>
   <elementGuidId>f3051f2b-5962-4608-8dc3-45a5630e3318</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.jut__RadioButton__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isAntique']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>df3bba12-9574-47ed-8820-7673fa34cf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>isAntique_true</value>
      <webElementGuid>527f1280-b326-4245-b6e5-08226d968a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>36825635-45c8-42a8-bf33-a949a8eddefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__RadioButton__label</value>
      <webElementGuid>f0af7f1f-ede4-4e80-8a98-0480cbffd6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>6d192f3d-2a0a-4f4d-9011-a2d327d3789c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isAntique&quot;)/div[@class=&quot;dynamicRadioButton__radioButton jut__RadioButton__radioButton jut__RadioButton__small&quot;]/label[@class=&quot;jut__RadioButton__label&quot;]</value>
      <webElementGuid>c8e40a41-5d64-4eb0-b5c0-30aa5a295dfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isAntique']/div/label</value>
      <webElementGuid>8dbbb818-da42-4978-a3bf-7bc153f37ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is auto plated as antique?'])[1]/following::label[1]</value>
      <webElementGuid>6e809a1f-fbe5-4fce-aaab-8573168d7a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MILANO GOLD'])[1]/following::label[2]</value>
      <webElementGuid>1fc9734b-1b69-428b-a522-6370f5b9b0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::label[1]</value>
      <webElementGuid>9b653d5a-6b4e-4469-b1c7-2e028dc68520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/label</value>
      <webElementGuid>96056bbe-08fa-459f-9dad-8b87b80ae060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>523b031c-057c-41c3-a65e-44ccf52d2645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
