<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_28th Street Southeast, Grand Rapids, MI, USA</name>
   <tag></tag>
   <elementGuidId>92d7cbed-432b-42b7-bffa-f22a03b1a19f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR.AddressLookupTypeaheadComponent_gw-typeahead__match_active__3f9Df</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='addressTypeAhead_address-j7fzorw11ld-googleAddressAPI_typeaheadDropdownList']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0f615a0b-45dc-4876-a440-98df8a97270a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>62d8aabf-7a31-4ed1-a1a2-6c3018f5aa4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>596ff6ee-3c1e-45c5-9b29-2fb71367ee51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR AddressLookupTypeaheadComponent_gw-typeahead__match_active__3f9Df</value>
      <webElementGuid>23bfc48f-5a83-4f9c-8b43-efe4d6b1c294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>28th Street Southeast, Grand Rapids, MI, USA</value>
      <webElementGuid>c8416292-5f6e-4e31-82bd-494a26aa5fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_address-j7fzorw11ld-googleAddressAPI_typeaheadDropdownList&quot;)/li[@class=&quot;AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR AddressLookupTypeaheadComponent_gw-typeahead__match_active__3f9Df&quot;]</value>
      <webElementGuid>848ac4a3-4c48-43e1-9982-a1d551da47f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='addressTypeAhead_address-j7fzorw11ld-googleAddressAPI_typeaheadDropdownList']/li</value>
      <webElementGuid>8d53c7c5-0632-4cdf-b11a-a2d289aa7530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::li[1]</value>
      <webElementGuid>d522256d-1295-4604-abac-5e7be97ac26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::li[1]</value>
      <webElementGuid>e4a10246-19b3-4ee2-81bf-f2376cbeabab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 2'])[1]/preceding::li[5]</value>
      <webElementGuid>f2c9f862-2645-4b30-b923-10de06978840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::li[5]</value>
      <webElementGuid>529f9df6-cd7c-4ac6-95fe-2d150d6b29ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='28th Street Southeast, Grand Rapids, MI, USA']/parent::*</value>
      <webElementGuid>f910a82a-efae-4b06-8920-d7d4e6cb3940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>8a2759a5-597e-4873-a835-1f66311734fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '28th Street Southeast, Grand Rapids, MI, USA' or . = '28th Street Southeast, Grand Rapids, MI, USA')]</value>
      <webElementGuid>fea28d97-0f95-4d8c-97fb-5fb351c6743e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
