<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Full Pay</name>
   <tag></tag>
   <elementGuidId>b2529fdc-3713-45c4-8c78-5a274070d10f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.jut__RadioButton__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='billingAndPaymentsCard']/div/div[2]/table/tbody/tr/td/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cbc0fc35-5811-4be1-acdb-30ebe6efc51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>paymentPlan_0_db_full_pay</value>
      <webElementGuid>257e1dee-4561-47ae-b6c3-e4917ccc2b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__RadioButton__label</value>
      <webElementGuid>bdc87a34-05c0-404d-8f3a-2d88ce5c0db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full Pay</value>
      <webElementGuid>6bc5ef1f-91f5-4146-a2a6-b64ddd758a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingAndPaymentsCard&quot;)/div[1]/div[@class=&quot;dynamicTable__table jut__Table__table jut__Table__hoverable hmic__Table__default hmic__Table__alternatingRowColorsFlipped PaymentStep_dataTable__2o3PO&quot;]/table[@class=&quot;jut__Table__tableElement&quot;]/tbody[1]/tr[@class=&quot;jut__Table__row&quot;]/td[@class=&quot;dynamicTable__tableCell jut__Table__tableCell text-left&quot;]/div[@class=&quot;dynamicRadioButton__radioButton jut__RadioButton__radioButton jut__Table__radio&quot;]/label[@class=&quot;jut__RadioButton__label&quot;]</value>
      <webElementGuid>ac766413-9636-458c-bb66-ae4254bb76a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billingAndPaymentsCard']/div/div[2]/table/tbody/tr/td/div/label</value>
      <webElementGuid>e7ebf02d-8b05-457d-b4c3-f18e519a7a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::label[1]</value>
      <webElementGuid>2e574dd2-3621-4c0e-b3ff-d418498555d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installments'])[1]/following::label[1]</value>
      <webElementGuid>71687de2-d896-4b7e-a37d-a421f5923818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$381.00'])[2]/preceding::label[1]</value>
      <webElementGuid>c973730f-9204-48db-a8ac-5c57460af670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/label</value>
      <webElementGuid>b9218c97-fe4e-44c2-9fd2-c612b67d18a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Full Pay' or . = 'Full Pay')]</value>
      <webElementGuid>be9b01ee-6349-4c60-ab2b-4f35d3599b6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
