<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save_jut__CheckboxField__checkboxElement</name>
   <tag></tag>
   <elementGuidId>f0476589-a86e-4799-b9ac-124436c67836</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renewChangePaymentPlanCard > div > div.jut__FieldComponent__fieldComponent.smallOverline > div.jut__FieldComponent__contentContainer.jut__FieldComponent__controls > div.jut__CheckboxField__checkbox > span.jut__CheckboxField__checkboxElement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='renewChangePaymentPlanCard']/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>862fa20e-9369-4b82-b88d-3b1377c0c590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__CheckboxField__checkboxElement</value>
      <webElementGuid>388692e7-4c10-46bb-b707-0914ff4435d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Change payment plan at renewal?</value>
      <webElementGuid>1ddb0468-a4a0-4852-be41-8fe3155a754d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3124bd8e-7287-4dce-8406-88ad47812f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>52db2ff4-2a69-42b1-b11d-3a12071fb8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d098222-f036-4901-a486-c87f4aba2b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renewChangePaymentPlanCard&quot;)/div[1]/div[@class=&quot;jut__FieldComponent__fieldComponent smallOverline&quot;]/div[@class=&quot;jut__FieldComponent__contentContainer jut__FieldComponent__controls&quot;]/div[@class=&quot;jut__CheckboxField__checkbox&quot;]/span[@class=&quot;jut__CheckboxField__checkboxElement&quot;]</value>
      <webElementGuid>8ea9fa20-69db-4f79-80a0-6c2f57a06209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renewChangePaymentPlanCard']/div/div/div/div/span</value>
      <webElementGuid>618112e9-8465-424f-9b78-0b13f9b8614c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span</value>
      <webElementGuid>4218185b-beef-4076-a6f0-da213de6290c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
