<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Address TypeBillingAddressAddress 2Addr_16ab90</name>
   <tag></tag>
   <elementGuidId>389d0d8c-fb09-4399-8112-950e0617eb80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jut__Grid__grid.jut__Grid__vgapMedium.jut__Grid__hgapMedium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90e3c2ca-45ce-4e6c-8b66-f83ddbfb4e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__Grid__grid jut__Grid__vgapMedium jut__Grid__hgapMedium</value>
      <webElementGuid>7a2619cc-98a7-4261-a6cc-014bdf867910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*Address TypeBilling*AddressAddress 2Address 3*CityStateState*ZIP Code</value>
      <webElementGuid>ed6d611a-8148-4d7e-a78b-49d170240f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;PageContainer_standard__3bPCs&quot;]/div[@class=&quot;QuoteWizard_container__3EESf&quot;]/div[1]/div[@class=&quot;Wizard_bottomContainer__3lWO5&quot;]/div[2]/div[1]/div[@class=&quot;WizardPanel_body__21TLo&quot;]/div[1]/div[1]/div[@class=&quot;CreateUpdateView_formContainer__XCC_-&quot;]/div[@class=&quot;FieldSet_container__3odpU&quot;]/div[2]/div[2]/div[@class=&quot;ContactForm_gridrow__1pOGG&quot;]/div[@class=&quot;ContactForm_span2__1V1So&quot;]/div[1]/div[@class=&quot;jut__Grid__grid jut__Grid__vgapMedium jut__Grid__hgapMedium&quot;]</value>
      <webElementGuid>3393a1c6-c10b-46d4-b6e4-d4d837457630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>12a51b11-8647-42ec-9a19-21112972f6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/following::div[7]</value>
      <webElementGuid>5273ec89-8690-40e8-ace0-1e26b878ff07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Type: Company'])[1]/following::div[12]</value>
      <webElementGuid>21fbfbe5-a19d-4c2c-a241-c3b7ea294033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>fbda29b4-0858-4dba-96b6-a2b0f244cd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '*Address TypeBilling*AddressAddress 2Address 3*CityStateState*ZIP Code' or . = '*Address TypeBilling*AddressAddress 2Address 3*CityStateState*ZIP Code')]</value>
      <webElementGuid>a770f9dd-4b67-4ba2-9b11-2e0ec6f205bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
