<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_addressTypeAhead_contact-6loz_8085f5</name>
   <tag></tag>
   <elementGuidId>605799bf-e5e1-4bf8-8518-e8adf6034d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressTypeAhead_contact-6lozjf4f77r-address-255fzycdiw9-googleAddressAPI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressTypeAhead_contact-6lozjf4f77r-address-255fzycdiw9-googleAddressAPI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>416de104-067d-4062-bb28-f4885be54fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-6lozjf4f77r-address-255fzycdiw9-googleAddressAPI</value>
      <webElementGuid>9ec408ef-3eff-4bf7-92aa-fac3ffb0748b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>750cf47d-a6dd-4d9e-abbf-62c8d255b065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>c9403c4e-f303-47bc-849a-aefe862f3ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-contact-6lozjf4f77r-address-255fzycdiw9 address-line1</value>
      <webElementGuid>d33fab06-ef73-4199-aadc-8fac2dcef9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f153994-c312-459e-976f-1fc8d2e3ac0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-6lozjf4f77r-address-255fzycdiw9-googleAddressAPI_1440013438</value>
      <webElementGuid>535bfee5-d03d-463c-b9b5-5ce06327794f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>7f8d818a-8698-4eb5-8641-da6514f7fb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>2e7068d2-d2f1-4330-91f4-40329a4e7ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_contact-6lozjf4f77r-address-255fzycdiw9-googleAddressAPI&quot;)</value>
      <webElementGuid>4303cd89-2554-4afd-920d-382b09a8b686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressTypeAhead_contact-6lozjf4f77r-address-255fzycdiw9-googleAddressAPI']</value>
      <webElementGuid>5c624277-96b5-421f-b8a1-878dd9676107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>feeaafe6-ce2f-45c8-bb07-475a7d807605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>2df73272-fdc6-443f-b37b-426000cf22d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressTypeAhead_contact-6lozjf4f77r-address-255fzycdiw9-googleAddressAPI' and @type = 'text' and @placeholder = 'Street address']</value>
      <webElementGuid>3ba597b7-55f9-4243-8bad-520f324b7daf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
