<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_404 East Woodlawn Avenue, Hastings, MI, USA</name>
   <tag></tag>
   <elementGuidId>5e72fff4-a568-459a-b0ca-91868b2ecb0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR.AddressLookupTypeaheadComponent_gw-typeahead__match_active__3f9Df</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='addressTypeAhead_contact-6lozjf4f77r-address-255fzycdiw9-googleAddressAPI_typeaheadDropdownList']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b4da32f6-3956-42dd-b744-443bc4d24de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e46ea242-a6e2-48c1-8166-67ac7074d234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>017d3f91-fb6d-41b7-9a39-d4b9ccadbe0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR AddressLookupTypeaheadComponent_gw-typeahead__match_active__3f9Df</value>
      <webElementGuid>f3438bd6-ad58-4e97-91cd-96f12c13c5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>404 East Woodlawn Avenue, Hastings, MI, USA</value>
      <webElementGuid>cc3328cb-da55-455b-860a-7d34bda56811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_contact-6lozjf4f77r-address-255fzycdiw9-googleAddressAPI_typeaheadDropdownList&quot;)/li[@class=&quot;AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR AddressLookupTypeaheadComponent_gw-typeahead__match_active__3f9Df&quot;]</value>
      <webElementGuid>6280d9ca-b481-4b47-a2bb-a1a184837469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='addressTypeAhead_contact-6lozjf4f77r-address-255fzycdiw9-googleAddressAPI_typeaheadDropdownList']/li</value>
      <webElementGuid>d3dbc26c-0251-415b-9462-5ab9407718ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::li[1]</value>
      <webElementGuid>21d94ddd-1cce-4f0d-bed9-d81ef7f1b6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing'])[2]/following::li[1]</value>
      <webElementGuid>1a8cf992-928e-4fe4-92c4-b84876df0cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 2'])[1]/preceding::li[5]</value>
      <webElementGuid>8ba72ea5-a624-488f-b8a7-c78113e04082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 3'])[1]/preceding::li[5]</value>
      <webElementGuid>24f25a27-9aa2-47dc-b8ae-991f8175bb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='404 East Woodlawn Avenue, Hastings, MI, USA']/parent::*</value>
      <webElementGuid>34babfb8-a02c-4977-8f24-0b5e7e4cbd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>5762dad6-1c4a-4e5e-87ed-cc783527e96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '404 East Woodlawn Avenue, Hastings, MI, USA' or . = '404 East Woodlawn Avenue, Hastings, MI, USA')]</value>
      <webElementGuid>45b4b514-3ca2-4649-81fa-b4fad633bede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
