<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QUOTE</name>
   <tag></tag>
   <elementGuidId>479da325-7065-4cf4-9773-bf70684457cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QUOTE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='QUOTE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e5b8d735-d665-4df6-ac07-09a809f9d3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-links left</value>
      <webElementGuid>101dc05a-a518-4a6d-804a-ee62168a442f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QUOTE</value>
      <webElementGuid>4227cce2-dbab-469d-a4f3-30945bfd6da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/agent-dashboard/openquotes</value>
      <webElementGuid>cc0920ee-a730-4bd8-a3ab-bceb3067cace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QUOTE</value>
      <webElementGuid>808be9af-5053-4b77-a917-80da253e4a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QUOTE&quot;)</value>
      <webElementGuid>bd14d500-a4b9-4187-ad45-00ca1092f4c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='QUOTE']</value>
      <webElementGuid>c29161ad-a00f-4845-b2d0-937da4499a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Contentplaceholder1_T99701C38002_Col00']/div[2]/div/div/a[2]</value>
      <webElementGuid>f60c6252-e595-41ba-98df-f4b946da91ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'QUOTE')]</value>
      <webElementGuid>f94742b4-0db0-499c-974d-f079ff00a685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME'])[1]/following::a[1]</value>
      <webElementGuid>e5775627-9d6f-4450-bf4a-046a0a795f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[2]</value>
      <webElementGuid>a6759750-3f43-486e-a782-deb97be5afd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCOUNTS'])[1]/preceding::a[1]</value>
      <webElementGuid>7a6fee0c-0ae1-4f94-9199-33f46cdcd37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLICIES'])[1]/preceding::a[2]</value>
      <webElementGuid>49d56ece-505b-41bb-b838-441b01520f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QUOTE']/parent::*</value>
      <webElementGuid>3a1169b4-0c04-4565-acb8-e3483f709b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/agent-dashboard/openquotes')]</value>
      <webElementGuid>bc9cf2de-0a32-42ad-b261-92e5fd88d83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>47f922d2-e98f-4028-9c58-5e6088df8de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'QUOTE' and @href = '/agent-dashboard/openquotes' and (text() = 'QUOTE' or . = 'QUOTE')]</value>
      <webElementGuid>329c19a3-8e48-419e-9f2a-c9e589dec6d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
